__Group: QuantParty  
Group members: Yanzhang Li, Oscar Chim, Jojo Liu, Jiani He, Chuanyu Lin__

<h1> Overview </h1>

Our group performs two directions in analyzing reversal in ETFS.  
The first one is "testing consistency for reversal strategy";   
the second one is "Study on reversal in ETFs with different market capitalization"

<h2> Testing Consistency for Reversal Strategy </h2>

<h3> Idea </h3>

The idea of "testing the consistency for reversal strategy" is to validate if a group of etfs performs a strong (weak) reversal characteristic in the history, whether they will continue to perform a strong (weak) reversal characteristic in the future?  
  
In general, there are several steps as follows.
- group the etfs according to historical reversal performance (100 days)
- focus on the group with strongest/weakest reversal
- test the reversal performance via 3 different regression methods for the next 20 days
- calculate the regression coefficient every 20 days, at the same time, update the grouping
- compare the historical and future performance (t-statistics for regression coefficient)

<h3> Methods </h3>

<h4> Setting Groups </h4>
- for each etf (total 550 etfs),run time series regression from t to t+100 (100 days)
$$ R_{t+1} =  b_0 + b_1*R_t+ e_t $$
- If there is a strong reversal, then b1 must be smaller than zero (assume benchmark = 0)
- We get in total 550 b1
- group the eft according to the value of b1 into 10 groups
- group 0 has the smallest b1, and group 9 has the largest b1


<h4> Testing reversal for group 0 and group 9 </h4>
- Run the following regression (general idea formula) within a given group from t+101 to t+120 (20 days)
$$ R_{t+1}= a_0+a_1*R_t+a_2*MA(5)_t $$
- R_t means the return for today, MA(5) is the average return for the past 5 days (including today)
- R_t+1 means the return for the next day
- Take group 0 as an example, if reversal is consistent, then a low a1 or a2 (or combination effect) will follows a low b1
- we examine the t statistics for a1 and a2

<h4> Regression methods </h4>
  
We perform 3 different regression methods for testing reversal, which are basically derived from the general idea formula above. 
  
a. portfolio method
- let the 55 etf in one group forms a portfolio
- R_t and MA(5) are both simple average for the 55 etfs data at given date t
- this could examine the overall effect of reversal for the given group
  
b. time demeaned method
- since the testing data are a panel data with 55 etfs and 20 days, there might be time fixed effect, which will weaken the validity of the estimate of coefficients
- to eliminate the time fixed effect, we improve the regresson as follows
$$ R_{t+1} - 1/S * \sum_{i=1}^S R_{t+1} = a_0+a_1* [R_t - 1/S * \sum_{i=1}^S R_{t}]+a_2*[MA(5)_{t} - 1/S * \sum_{i=1}^S MA(5)_{t}] $$
- By subtracting the average value for 55 efts (here S = 55) in a given date, we can eliminate the time fixed effect
- we can also interpret this regression formula as how a particular etf outperform the benchmark (average value in the group) in reversal
- this regression runs 1100 rows of data in one time (55 * 20)  
   
c. Fama_Macbeth method
- In Fama method, for the 20 days testing data, we run regression on one day for 20 times (t+101 to t+120), each regression include 55 etfs data
- average the 20 estimates of coefficients using Fama_Macbeth technique
$$ a_{fama} = 1/T * \sum_{i=1}^T a_{t} $$
- it can improve the residual correlation problem in OLS

<h4> Rolling throughout whole dataframe </h4>
  
- get the coefficient estimates for every 20 days
- update the groups every 20 days
- for example: 
- t = 1 to t = 100: get the first 550 b1 and form the first 10 groups
- t = 101 to t = 120: get the first estimate of a1 and a2
- t = 20 to t = 120: get the second 550 b1 and form the second 10 groups
- t = 121 to t = 140: get the second estimate of a1 and a2
  
- in general, there are 139 estimates of a1 and a2 for the whole dataframe ( (2893 - 120)/20 +1 = 139.65)

<h3> Notes </h3>

you can skip the part "try on the first set of dates"  
- this part provide how I examine the idea to get the first estimates of a1 and a2 (using data from day 1 to day 100 for grouping, and data from day 101 to 120 for estimating the first set of coefficients)
- the final result of the data set is not generated from this part
- results are running from the for loop parts (the generalized part of "try on the first set of dates")

The for loop parts takes a lot of time to run. Each for loop gets 139 estimates of a1 and a2, which needs to perform a lot of regression for the whole data set (2893 days).
- in my computer, it takes around 10 minutes for each for loop.
- There are 6 for loops in total (3 methods * 2 group)

<h3> Generates a Portfolio </h3>

build a portfolio according to the testing results  
- Focus on the etfs in the group with strongest reversal
- Long the etfs with bottom 20% current day return, short the etfs with top 20% current day return
- Examine the portfolio performance by testing the next day return

<h2> Study on reversal in ETFs with different market capitalization</h2>

<h3> Idea </h3>

The idea of ‘study on reversal in ETFs with different market capitalization’ is to compute reversal performance with companies with different market capitalization and whether big companies and small ones have the same reversal effect？Whether the time period will affect the reversal performance?

In general, there are several steps as follows.

- Divide the 548 ETFs into 4 groups according to their market cap(from smallest to largest)
- Test the reversal performance for each group by regressing returns on lagged returns
- Compare coefficients and validate the significance( t-test)
- Further confirm a longer horizon reversal

<h3> Methods </h3>

<h4> Setting Groups </h4>

- Calculate lagged return and drop ETFs which has unavailable data, finally each date (for 2892 days) consist of exactly 548 ETF data
- Calculate market cap : $$MKTCAP = SHROUT* |PRC|$$
- Divide ETFs into 4 groups by market cap (137 ETFs/each group), smallest ones are 1, and largest ones are 4

<h4> Testing reversal for group 1 to 4 </h4>

- Making hypothesis:  
 H0: Large Market cap (top 25%) and Small Market cap (bottom 25%) ETFs have the same reversal effect.  
 H1: Large Market cap (top 25%) has a smaller reversal effect than the Small Market cap ETFs (bottom 25%).

- Run the following regression for different groups:
$$ R_{t+1} =  b_0 + b_1*R_t+ e_t $$
R_t means the return for today，R_t+1 means the return for the next day
- Examine the t statistics for b1 for each group

<h4> Testing difference between group 1 and group 4 </h4>

- Calculate difference lagret between smallest and lagest market cap group
- We examine the t statistics for new b1

<h4> Take a long term look for reversal performance in small cap  </h4>

- Pick weekly data from daily data by using the day of the week
- Calulate new lagged return and drop unavailable ones
- Divide ETFs into 4 groups by new market cap
- Run the following regression for different groups:
$$ R_{t+1} =  b_0 + b_1*R_t+ e_t $$
- Examine the t statistics for b1 for each group
- Calculate difference between smallest and lagest market cap group

<h4> Analyze a new portofolio </h4>

- Build a portfolio that only contains ETFs with a small cap
- Subdivision groups by using lagged return
- Calculate average return
- Sell ETFs with highest return and buy ETFs with lowest return
- Calculate mean, standard deviation and sharpe ratio

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind
import statistics
import statsmodels.formula.api as smf

<h1> General Data Cleaning </h1>

In [2]:
data = pd.read_feather('etfdata_new.feather')
data

PERMNO       DATE              COMNAM   TICKER  SHRCD   SICCD  \
0         10001.0 2000-01-03  b'ENERGY WEST INC'  b'EWST'   11.0  4920.0   
1         10001.0 2000-01-04  b'ENERGY WEST INC'  b'EWST'   11.0  4920.0   
2         10001.0 2000-01-05  b'ENERGY WEST INC'  b'EWST'   11.0  4920.0   
3         10001.0 2000-01-06  b'ENERGY WEST INC'  b'EWST'   11.0  4920.0   
4         10001.0 2000-01-07  b'ENERGY WEST INC'  b'EWST'   11.0  4920.0   
...           ...        ...                 ...      ...    ...     ...   
41342432  93436.0 2022-06-24        b'TESLA INC'  b'TSLA'   11.0  9999.0   
41342433  93436.0 2022-06-27        b'TESLA INC'  b'TSLA'   11.0  9999.0   
41342434  93436.0 2022-06-28        b'TESLA INC'  b'TSLA'   11.0  9999.0   
41342435  93436.0 2022-06-29        b'TESLA INC'  b'TSLA'   11.0  9999.0   
41342436  93436.0 2022-06-30        b'TESLA INC'  b'TSLA'   11.0  9999.0   

                 PRC         VOL     OPENPRC       ASKHI       BIDLO  \
0           8.562500      1721.0    8.437500    8.562500    8.437500   
1           8.437500      1080.0    8.437500    8.437500    8.437500   
2           8.562500      1711.0    8.437500    8.562500    8.437500   
3           8.500000       580.0    8.500000    8.500000    8.500000   
4           8.437500      1406.0    8.562500    8.562500    8.437500   
...              ...         ...         ...         ...         ...   
41342432  737.119995  31784681.0  712.405029  738.200012  708.260010   
41342433  734.760010  29594364.0  748.099976  756.210022  727.696594   
41342434  697.989990  30073839.0  733.450012  749.909973  697.030029   
41342435  685.469971  27513141.0  691.500000  693.520020  666.820007   
41342436  673.419983  31340783.0  673.530029  688.369995  656.590027   

                 BID         ASK       RET      RETX     SHROUT  DIVAMT  
0           8.437500    8.562500  0.007353  0.007353     2450.0     NaN  
1           8.437500    8.562500 -0.014599 -0.014599     2450.0     NaN  
2           8.437500    8.562500  0.014815  0.014815     2450.0     NaN  
3           8.437500    8.562500 -0.007299 -0.007299     2450.0     NaN  
4           8.437500    8.562500 -0.007353 -0.007353     2450.0     NaN  
...              ...         ...       ...       ...        ...     ...  
41342432  736.890015  737.640015  0.045249  0.045249  1036010.0     NaN  
41342433  734.630005  734.909973 -0.003202 -0.003202  1036010.0     NaN  
41342434  697.789978  698.099976 -0.050044 -0.050044  1036010.0     NaN  
41342435  685.150024  685.460022 -0.017937 -0.017937  1036010.0     NaN  
41342436  673.989990  674.210022 -0.017579 -0.017579  1036010.0     NaN  

[41342437 rows x 17 columns]

There are 21419 unique permnos in the etfdata_new.feather or data table.

In [3]:
a = data.PERMNO.unique()
len(a)

21419

Only ETFs (SHRCD = 73) are remained in the etf_data table.

In [4]:
etf_data = data.loc[data['SHRCD'] == 73]
etf_data

PERMNO       DATE                     COMNAM   TICKER  SHRCD  \
85746     10113.0 2010-07-21     b'ADVISORSHARES TRUST'  b'AADR'   73.0   
85747     10113.0 2010-07-22     b'ADVISORSHARES TRUST'  b'AADR'   73.0   
85748     10113.0 2010-07-23     b'ADVISORSHARES TRUST'  b'AADR'   73.0   
85749     10113.0 2010-07-26     b'ADVISORSHARES TRUST'  b'AADR'   73.0   
85750     10113.0 2010-07-27     b'ADVISORSHARES TRUST'  b'AADR'   73.0   
...           ...        ...                        ...      ...    ...   
41309807  93421.0 2022-06-24  b'INVESCO E T F TRUST II'  b'PICB'   73.0   
41309808  93421.0 2022-06-27  b'INVESCO E T F TRUST II'  b'PICB'   73.0   
41309809  93421.0 2022-06-28  b'INVESCO E T F TRUST II'  b'PICB'   73.0   
41309810  93421.0 2022-06-29  b'INVESCO E T F TRUST II'  b'PICB'   73.0   
41309811  93421.0 2022-06-30  b'INVESCO E T F TRUST II'  b'PICB'   73.0   

           SICCD        PRC       VOL    OPENPRC      ASKHI      BIDLO  \
85746     6726.0  24.700001   42000.0  25.100000  25.100000  24.700001   
85747     6726.0  25.260000   17500.0  25.420000  25.420000  25.129999   
85748     6726.0  25.280001    8600.0  25.540001  25.540001  25.080000   
85749     6726.0  25.370001   18900.0  25.400000  25.400000  25.219999   
85750     6726.0  25.290001    8200.0  25.250000  25.290001  25.200001   
...          ...        ...       ...        ...        ...        ...   
41309807  6726.0  22.270000   27076.0  22.120001  22.270000  22.110001   
41309808  6726.0  22.070000   47110.0  22.110001  22.190001  22.070000   
41309809  6726.0  21.870001  149537.0  21.950001  21.959999  21.840000   
41309810  6726.0  21.820000  395575.0  21.760000  21.865000  21.730000   
41309811  6726.0  22.030001  223681.0  21.879999  22.110001  21.860001   

                BID        ASK       RET      RETX  SHROUT  DIVAMT  
85746     24.650000  24.730000       NaN       NaN   100.0     NaN  
85747     25.129999  25.260000  0.022672  0.022672   100.0     NaN  
85748     25.030001  25.280001  0.000792  0.000792   100.0     NaN  
85749     25.350000  25.500000  0.003560  0.003560   100.0     NaN  
85750     24.990000  25.299999 -0.003153 -0.003153   100.0     NaN  
...             ...        ...       ...       ...     ...     ...  
41309807  22.219999  22.260000  0.011353  0.011353  5250.0     NaN  
41309808  22.070000  22.080000 -0.008981 -0.008981  5250.0     NaN  
41309809  21.870001  21.889999 -0.009062 -0.009062  5250.0     NaN  
41309810  21.820000  21.870001 -0.002286 -0.002286  5250.0     NaN  
41309811  22.030001  22.070000  0.009624  0.009624  5250.0     NaN  

[6021542 rows x 17 columns]

Only data after 2011 are considered since about 10 years data should be sufficient for us to study the reversal pattern without looking far back to the past that can be irrelevant.

Only ETFs existed for 2893 days are chosen, and they are likely to be contemporaneous (need validation).

We realized that there are 550 permnos for etf that existed for 2893 days.

In [5]:
data_2011 = etf_data.loc[etf_data['DATE'] > '2011-01-01']
etf_test = pd.DataFrame(data_2011.groupby('PERMNO')['DATE'].count())
permno = etf_test.loc[etf_test['DATE'] == 2893]
permno.index

Float64Index([10113.0, 11264.0, 11407.0, 11996.0, 12035.0, 12059.0, 12064.0,
              12065.0, 12098.0, 12105.0,
              ...
              93362.0, 93363.0, 93364.0, 93365.0, 93366.0, 93367.0, 93376.0,
              93377.0, 93378.0, 93379.0],
             dtype='float64', name='PERMNO', length=550)

get the list of PERMNO for the 550 etfs

In [6]:
list_permno = permno.index.tolist()
len(list_permno)

550

clean the dataframe by only including the data with the given 550 etfs  
We only need returns, volume, bid_low, ask_high, shares_of_outstanding for further analysis  
so drop the other columns
The following output shows that there are 2893 days * 550 etfs = 1591150 rows of data

In [7]:
df_etfs = data_2011[data_2011['PERMNO'].isin(list_permno)]
df_etfs = df_etfs.drop(columns=['COMNAM','SICCD','PRC','OPENPRC','BID','ASK','RETX','DIVAMT','SHRCD'])
df_etfs.index = range(len(df_etfs))
df_etfs

PERMNO       DATE   TICKER       VOL      ASKHI      BIDLO  \
0        10113.0 2011-01-03  b'AADR'    1600.0  30.063000  29.879999   
1        10113.0 2011-01-04  b'AADR'   22200.0  30.350000  29.910000   
2        10113.0 2011-01-05  b'AADR'   14000.0  29.898001  29.800100   
3        10113.0 2011-01-06  b'AADR'   13200.0  29.850000  29.740000   
4        10113.0 2011-01-07  b'AADR'    1600.0  29.740000  29.670000   
...          ...        ...      ...       ...        ...        ...   
1591145  93379.0 2022-06-24  b'EPOL'  106848.0  14.640000  14.360000   
1591146  93379.0 2022-06-27  b'EPOL'  140237.0  14.880000  14.690500   
1591147  93379.0 2022-06-28  b'EPOL'  166483.0  15.060000  14.585000   
1591148  93379.0 2022-06-29  b'EPOL'   55073.0  14.870000  14.660000   
1591149  93379.0 2022-06-30  b'EPOL'   66227.0  14.690000  14.340000   

              RET   SHROUT  
0        0.007473    275.0  
1       -0.001763    275.0  
2       -0.005998    275.0  
3        0.000000    275.0  
4       -0.005364    275.0  
...           ...      ...  
1591145  0.027503  11600.0  
1591146  0.013041  11600.0  
1591147 -0.004065  11600.0  
1591148  0.002721  11600.0  
1591149 -0.007463  10700.0  

[1591150 rows x 8 columns]

__get the clean data for further analysis__

In [9]:
etf_clean = df_etfs.set_index(['DATE','PERMNO'])
etf_clean = etf_clean.sort_index()  

In [10]:
etf_clean

TICKER       VOL      ASKHI      BIDLO       RET   SHROUT
DATE       PERMNO                                                             
2011-01-03 10113.0  b'AADR'    1600.0  30.063000  29.879999  0.007473    275.0
           11264.0  b'RETL'     600.0  58.571301  58.169998  0.020051    100.0
           11407.0   b'LIT'  554600.0  23.659000  23.000000  0.038259   6200.0
           11996.0  b'EMLC'  164200.0  26.719999  26.570000 -0.003301    200.0
           12035.0  b'AMLP'  928100.0  16.170000  16.080000  0.003111  35150.0
...                     ...       ...        ...        ...       ...      ...
2022-06-30 93367.0  b'PSCD'    1299.0  75.150002  74.610001 -0.016505    340.0
           93376.0  b'EUSA'   21891.0  71.074997  69.839996 -0.007586   5550.0
           93377.0  b'EIDO'  683100.0  22.385000  22.100000 -0.001339  19500.0
           93378.0  b'EIRL'   13190.0  40.479698  39.490002 -0.010272   1200.0
           93379.0  b'EPOL'   66227.0  14.690000  14.340000 -0.007463  10700.0

[1591150 rows x 6 columns]

The following output shows there is no missing dates for the 550 etfs in 2893 days

In [11]:
test_etf_count = etf_clean['TICKER'].groupby('DATE').count()
test_etf_count.describe()

count    2893.0
mean      550.0
std         0.0
min       550.0
25%       550.0
50%       550.0
75%       550.0
max       550.0
Name: TICKER, dtype: float64

<h1> Testing Consistency for Reversal Strategy </h1>

<h2> Data Processing </h2>

we only need the column return in the new data frame

In [12]:
etf_reversal = etf_clean[['RET']]
etf_reversal['LAGRET'] = etf_reversal['RET'].groupby('PERMNO').shift()
etf_reversal.reorder_levels(['PERMNO','DATE'])
etf_reversal.sort_index(level=1)

<ipython-input-12-97a27ce778e8>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  etf_reversal['LAGRET'] = etf_reversal['RET'].groupby('PERMNO').shift()


RET    LAGRET
DATE       PERMNO                     
2011-01-03 10113.0  0.007473       NaN
2011-01-04 10113.0 -0.001763  0.007473
2011-01-05 10113.0 -0.005998 -0.001763
2011-01-06 10113.0  0.000000 -0.005998
2011-01-07 10113.0 -0.005364  0.000000
...                      ...       ...
2022-06-24 93379.0  0.027503 -0.021394
2022-06-27 93379.0  0.013041  0.027503
2022-06-28 93379.0 -0.004065  0.013041
2022-06-29 93379.0  0.002721 -0.004065
2022-06-30 93379.0 -0.007463  0.002721

[1591150 rows x 2 columns]

get the column of MA5

In [13]:
etf_reversal['MA5'] = etf_reversal.groupby('PERMNO')['LAGRET'].transform(lambda x: x.rolling(5, 5).mean())

<ipython-input-13-c8f8389be902>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  etf_reversal['MA5'] = etf_reversal.groupby('PERMNO')['LAGRET'].transform(lambda x: x.rolling(5, 5).mean())


drop the nan value (the first 5 days)  
__reg_data is the dataframe built for rolling regression, it will not change__

In [14]:
reg_data = etf_reversal
reg_data.reset_index(inplace=True)
reg_data = reg_data.loc[reg_data['DATE']> '2011-01-07']
reg_data

DATE   PERMNO       RET    LAGRET       MA5
2750    2011-01-10  10113.0 -0.000741 -0.005364 -0.001130
2751    2011-01-10  11264.0  0.004172 -0.002479 -0.007964
2752    2011-01-10  11407.0  0.000224 -0.002903 -0.003422
2753    2011-01-10  11996.0 -0.010267  0.000453 -0.001245
2754    2011-01-10  12035.0  0.002607  0.001246  0.000002
...            ...      ...       ...       ...       ...
1591145 2022-06-30  93367.0 -0.016505 -0.017668  0.004449
1591146 2022-06-30  93376.0 -0.007586 -0.006005  0.003792
1591147 2022-06-30  93377.0 -0.001339 -0.013644 -0.004266
1591148 2022-06-30  93378.0 -0.010272 -0.011715 -0.001824
1591149 2022-06-30  93379.0 -0.007463  0.002721  0.003561

[1588400 rows x 5 columns]

In [15]:
reg_data.index = range(len(reg_data))

<h2> Try on the first set of dates </h2>

test the idea on day 1 to day 120, if works, then just put them into a for loop to run the whole dataframe

use the first 100 days to run regression  
get the list of date from low to high for the whole data set

<h3> First we test the portfolio method </h3>

In [17]:
get_date = pd.DataFrame(reg_data.groupby('DATE')['PERMNO'].count())
list_date = get_date.index.tolist()
len(list_date)

2888

use the first 100 days get the required data for the first regression, reg_data_1 is the data for getting the first group

In [18]:
list_date_1 = list_date[:100]
reg_data_1 = reg_data[reg_data['DATE'].isin(list_date_1)]
reg_data_1

DATE   PERMNO       RET    LAGRET       MA5
0     2011-01-10  10113.0 -0.000741 -0.005364 -0.001130
1     2011-01-10  11264.0  0.004172 -0.002479 -0.007964
2     2011-01-10  11407.0  0.000224 -0.002903 -0.003422
3     2011-01-10  11996.0 -0.010267  0.000453 -0.001245
4     2011-01-10  12035.0  0.002607  0.001246  0.000002
...          ...      ...       ...       ...       ...
54995 2011-06-02  93367.0 -0.014879 -0.029550  0.003001
54996 2011-06-02  93376.0 -0.005273 -0.021346  0.001341
54997 2011-06-02  93377.0  0.005120 -0.015748  0.002166
54998 2011-06-02  93378.0  0.002120  0.010494  0.008294
54999 2011-06-02  93379.0  0.019989 -0.023679  0.007305

[55000 rows x 5 columns]

Now get the beta to further group the eths into 10 groups

In [19]:
def regfun(df, mod):
    results = smf.ols(mod, data=df).fit()
    return results.params

In [20]:
allparams = reg_data_1.groupby('PERMNO').apply(regfun, 'RET ~ LAGRET')

group the parameter into 10 groups

In [21]:
allparams['QUINTILE'] = pd.qcut(allparams.LAGRET,10,labels=False)
allparams

Intercept    LAGRET  QUINTILE
PERMNO                                
10113.0   0.000741 -0.077270         0
11264.0   0.000752 -0.008101         2
11407.0  -0.000683  0.159864         9
11996.0   0.000643 -0.000478         2
12035.0   0.000099  0.257362         9
...            ...       ...       ...
93367.0   0.000282  0.081551         6
93376.0   0.000586 -0.132797         0
93377.0   0.001090  0.119103         8
93378.0   0.001556  0.061034         6
93379.0   0.001964 -0.061146         1

[550 rows x 3 columns]

get the first b1 for the lowest beta group

In [23]:
group_0 = allparams.loc[allparams['QUINTILE'] == 0]
group_0_beta = group_0['LAGRET'].mean()
group_0_beta

-0.1700413431171783

get the first test dataset: etf lays in group 0 and for the 101 to 120 dates

In [24]:
group_0_etf_list = group_0.index.to_list()
list_date_test_1 = list_date[100:120]
test_data_1 = reg_data[reg_data['DATE'].isin(list_date_test_1) & reg_data['PERMNO'].isin(group_0_etf_list) ]
test_data_1

DATE   PERMNO       RET    LAGRET       MA5
55000 2011-06-03  10113.0  0.001042  0.007219  0.004477
55005 2011-06-03  12059.0  0.002131 -0.003813  0.001526
55006 2011-06-03  12064.0  0.000596 -0.000755  0.000209
55013 2011-06-03  12289.0  0.000099 -0.002278  0.000758
55020 2011-06-03  12302.0 -0.013448 -0.002873 -0.000583
...          ...      ...       ...       ...       ...
65961 2011-06-30  93217.0 -0.003938 -0.012878 -0.009662
65962 2011-06-30  93218.0 -0.004062 -0.013374 -0.004005
65967 2011-06-30  93253.0 -0.000622  0.000714  0.000168
65979 2011-06-30  93292.0 -0.002235 -0.012141 -0.001053
65996 2011-06-30  93376.0  0.009844  0.009577  0.000500

[1100 rows x 5 columns]

aggregate the mean for the 55 etfs in a given day

In [25]:
try1 = test_data_1.groupby('DATE').agg('mean')
try1

PERMNO       RET    LAGRET       MA5
DATE                                                  
2011-06-03  84860.654545 -0.000221 -0.001958  0.000340
2011-06-06  84860.654545 -0.002740 -0.000221 -0.000153
2011-06-07  84860.654545  0.000409 -0.002740 -0.001101
2011-06-08  84860.654545 -0.000889  0.000409 -0.001584
2011-06-09  84860.654545  0.000977 -0.000889 -0.001080
2011-06-10  84860.654545 -0.003376  0.000977 -0.000493
2011-06-13  84860.654545 -0.001094 -0.003376 -0.001124
2011-06-14  84860.654545  0.002085 -0.001094 -0.000795
2011-06-15  84860.654545 -0.001870  0.002085 -0.000460
2011-06-16  84860.654545 -0.000775 -0.001870 -0.000656
2011-06-17  84860.654545  0.001822 -0.000775 -0.001006
2011-06-20  84860.654545  0.000859  0.001822  0.000034
2011-06-21  84860.654545  0.002834  0.000859  0.000424
2011-06-22  84860.654545 -0.000373  0.002834  0.000574
2011-06-23  84860.654545 -0.002543 -0.000373  0.000874
2011-06-24  84860.654545 -0.001839 -0.002543  0.000520
2011-06-27  84860.654545 -0.000601 -0.001839 -0.000212
2011-06-28  84860.654545  0.001187 -0.000601 -0.000504
2011-06-29  84860.654545  0.001971  0.001187 -0.000834
2011-06-30  84860.654545  0.000959  0.001971 -0.000365

run the first test data regression to get the estimate of a0 and a1

In [26]:
test_reg_result = regfun(try1, 'RET ~ LAGRET + MA5')

In [27]:
test_reg_result

Intercept   -0.000362
LAGRET       0.138590
MA5         -0.641626
dtype: float64

<h3> Second, we test the time_demeaned method </h3>

continue with previous test, now we need to merge the "test_data_1" with the daily mean dataset "try1"

In [29]:
try_1_left = test_data_1.set_index('DATE')
test_data_1_merge = try_1_left
test_data_1_merge[['RET_m','LAGRET_m','MA5_m']] = try1[['RET','LAGRET','MA5']]
test_data_1_merge

PERMNO       RET    LAGRET       MA5     RET_m  LAGRET_m  \
DATE                                                                    
2011-06-03  10113.0  0.001042  0.007219  0.004477 -0.000221 -0.001958   
2011-06-03  12059.0  0.002131 -0.003813  0.001526 -0.000221 -0.001958   
2011-06-03  12064.0  0.000596 -0.000755  0.000209 -0.000221 -0.001958   
2011-06-03  12289.0  0.000099 -0.002278  0.000758 -0.000221 -0.001958   
2011-06-03  12302.0 -0.013448 -0.002873 -0.000583 -0.000221 -0.001958   
...             ...       ...       ...       ...       ...       ...   
2011-06-30  93217.0 -0.003938 -0.012878 -0.009662  0.000959  0.001971   
2011-06-30  93218.0 -0.004062 -0.013374 -0.004005  0.000959  0.001971   
2011-06-30  93253.0 -0.000622  0.000714  0.000168  0.000959  0.001971   
2011-06-30  93292.0 -0.002235 -0.012141 -0.001053  0.000959  0.001971   
2011-06-30  93376.0  0.009844  0.009577  0.000500  0.000959  0.001971   

               MA5_m  
DATE                  
2011-06-03  0.000340  
2011-06-03  0.000340  
2011-06-03  0.000340  
2011-06-03  0.000340  
2011-06-03  0.000340  
...              ...  
2011-06-30 -0.000365  
2011-06-30 -0.000365  
2011-06-30 -0.000365  
2011-06-30 -0.000365  
2011-06-30 -0.000365  

[1100 rows x 7 columns]

get the demeaned regression variables

In [30]:
test_data_1_merge['RET_demean'] = test_data_1_merge['RET'] - test_data_1_merge['RET_m']
test_data_1_merge['LAGRET_demean'] = test_data_1_merge['LAGRET'] - test_data_1_merge['LAGRET_m']
test_data_1_merge['MA5_demean'] = test_data_1_merge['MA5'] - test_data_1_merge['MA5_m']
test_data_1_merge.head()

PERMNO       RET    LAGRET       MA5     RET_m  LAGRET_m  \
DATE                                                                    
2011-06-03  10113.0  0.001042  0.007219  0.004477 -0.000221 -0.001958   
2011-06-03  12059.0  0.002131 -0.003813  0.001526 -0.000221 -0.001958   
2011-06-03  12064.0  0.000596 -0.000755  0.000209 -0.000221 -0.001958   
2011-06-03  12289.0  0.000099 -0.002278  0.000758 -0.000221 -0.001958   
2011-06-03  12302.0 -0.013448 -0.002873 -0.000583 -0.000221 -0.001958   

              MA5_m  RET_demean  LAGRET_demean  MA5_demean  
DATE                                                        
2011-06-03  0.00034    0.001263       0.009177    0.004137  
2011-06-03  0.00034    0.002352      -0.001855    0.001186  
2011-06-03  0.00034    0.000818       0.001204   -0.000131  
2011-06-03  0.00034    0.000321      -0.000320    0.000418  
2011-06-03  0.00034   -0.013226      -0.000915   -0.000922

In [32]:
test_merge_result = regfun(test_data_1_merge, 'RET_demean ~ LAGRET_demean + MA5_demean')
test_merge_result

Intercept       -1.490778e-19
LAGRET_demean   -1.279603e-02
MA5_demean      -1.907743e-01
dtype: float64

<h3> Last, we test the Fama method </h3>

setup three list to fill in the regression coefficient for each date (will have length of 20 in the end)

In [34]:
beta_RET_list = []
beta_MA5_list = []
intercept_list = []

get test data from day 101 to day 120

In [35]:
list_date_fama = list_date[100:120]
test_data_fama = reg_data[reg_data['DATE'].isin(list_date_fama) & reg_data['PERMNO'].isin(group_0_etf_list) ]

use a for loop to fill in the coefficient lists

In [36]:
for i in range(100,120):
    list_date_fama_i = list_date[i]
    test_data_fama_i = test_data_fama.loc[test_data_fama['DATE']==list_date_fama_i]
    test_fama_result = regfun(test_data_fama_i, 'RET ~ LAGRET + MA5')
    beta_RET_list.append(test_fama_result['LAGRET'])
    beta_MA5_list.append(test_fama_result['MA5'])
    intercept_list.append(test_fama_result['Intercept'])

In [37]:
beta_MA5_fama = statistics.fmean(beta_MA5_list)
beta_MA5_fama

-0.38028892498834566

__Test is done for the first period (day 1 to day 120)__

<h2> Run regression for the whole dataframe </h2>

__Note that there are 6 loop in this part__
- 3 regression methods corresponding to 2 groups (lowest and highest)
- each loop takes about 10 minutes to run in my computer
- For detail comments, please refer to part 3. There is detailed explanation for each steps in the loop.

<h3> Loop 1: Portfolio method, strongest reversal group </h3>

In [38]:
df_compare_beta = pd.DataFrame(columns= ['Current_Date', 'beta_RET_1_100',
                                         'intercept_1_100','beta_RET_101_120','beta_MA5_101_120','intercept_101_120'])

In [40]:
for i in range(0,len(list_date)-120,20):
    list_date_i = list_date[i:i+100]
    reg_data_i = reg_data[reg_data['DATE'].isin(list_date_i)]
    allparams_i = reg_data_i.groupby('PERMNO').apply(regfun, 'RET ~ LAGRET')
    allparams_i['QUINTILE'] = pd.qcut(allparams_i.LAGRET,10,labels=False)
    group_0_i = allparams_i.loc[allparams_i['QUINTILE'] == 0]
    group_0_i_beta = group_0_i['LAGRET'].mean()   #b1
    group_0_i_intercept = group_0_i['Intercept'].mean()  #b0
    group_0_i_etf_list = group_0_i.index.to_list()
    list_date_test_i = list_date[i+100:i+120]
    test_data_i = reg_data[reg_data['DATE'].isin(list_date_test_i) & reg_data['PERMNO'].isin(group_0_i_etf_list) ]
    df_reg_test_i = test_data_i.groupby('DATE').agg('mean')
    test_reg_result_i = regfun(df_reg_test_i, 'RET ~ LAGRET + MA5')
    group_0_i_test_beta_1 = test_reg_result_i['LAGRET']  # a1
    group_0_i_test_beta_2 = test_reg_result_i['MA5']     # a2
    group_0_i_test_intercept = test_reg_result_i['Intercept']  #a0
    current_date = list_date[i+120]
    df_compare_beta = df_compare_beta.append({'Current_Date' : current_date, 'beta_RET_1_100' : group_0_i_beta, 
                                              'intercept_1_100' : group_0_i_intercept, 'beta_RET_101_120' : group_0_i_test_beta_1,
                                              'beta_MA5_101_120' : group_0_i_test_beta_2, 'intercept_101_120' : group_0_i_test_intercept}, 
                ignore_index = True)

df_compare_beta 

Current_Date  beta_RET_1_100  intercept_1_100  beta_RET_101_120  \
0     2011-07-01       -0.170041     3.352956e-04          0.138590   
1     2011-08-01       -0.156056     1.460491e-04         -0.014174   
2     2011-08-29       -0.130097     9.806446e-05         -0.259515   
3     2011-09-27       -0.372890    -1.028800e-03          0.379127   
4     2011-10-25       -0.306070    -1.239271e-03         -0.195838   
..           ...             ...              ...               ...   
134   2022-02-24       -0.180961    -6.361183e-04          0.436404   
135   2022-03-24       -0.144030     3.980642e-07          0.276125   
136   2022-04-22       -0.133236    -1.932585e-04         -0.278352   
137   2022-05-20       -0.126537    -6.343583e-05          0.143869   
138   2022-06-21       -0.131713    -1.284184e-03          0.039569   

     beta_MA5_101_120  intercept_101_120  
0           -0.641626          -0.000362  
1           -0.199061          -0.000108  
2           -0.436064          -0.002403  
3           -0.929376          -0.001209  
4           -0.876649           0.004121  
..                ...                ...  
134         -1.021402          -0.000410  
135         -0.534289           0.000718  
136          0.025223          -0.000354  
137         -0.414005          -0.001966  
138          0.253661          -0.001033  

[139 rows x 6 columns]

In [41]:
df_compare_beta.describe()

beta_RET_1_100  intercept_1_100  beta_RET_101_120  beta_MA5_101_120  \
count      139.000000       139.000000        139.000000        139.000000   
mean        -0.219058         0.000283         -0.040500         -0.381835   
std          0.065337         0.000599          0.238559          0.679943   
min         -0.479472        -0.001335         -0.770630         -2.643148   
25%         -0.243637        -0.000040         -0.216705         -0.753764   
50%         -0.208351         0.000311         -0.022117         -0.420323   
75%         -0.177606         0.000647          0.149749          0.048711   
max         -0.063211         0.002748          0.604566          2.016724   

       intercept_101_120  
count         139.000000  
mean            0.000474  
std             0.001680  
min            -0.004769  
25%            -0.000432  
50%             0.000302  
75%             0.001228  
max             0.006556

build a dataframe of 139 zeros to do the further t-test

In [42]:
df_zeros = pd.DataFrame(np.zeros((139, 1)),columns=['a'])

__t_test results of a1 and a2__

In [43]:
ttest_ind(df_compare_beta['beta_RET_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-2.001531279650405, pvalue=0.04631388643991064)

In [44]:
ttest_ind(df_compare_beta['beta_MA5_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-6.620804589287021, pvalue=1.857653585659878e-10)

<h3> Loop 2: Portfolio method, weakest reversal group </h3>

In [45]:
df_compare_beta_high = pd.DataFrame(columns= ['Current_Date', 'beta_RET_1_100',
                                         'intercept_1_100','beta_RET_101_120','beta_MA5_101_120','intercept_101_120'])

In [46]:
for i in range(0,len(list_date)-120,20):
    list_date_i = list_date[i:i+100]
    reg_data_i = reg_data[reg_data['DATE'].isin(list_date_i)]
    allparams_i = reg_data_i.groupby('PERMNO').apply(regfun, 'RET ~ LAGRET')
    allparams_i['QUINTILE'] = pd.qcut(allparams_i.LAGRET,10,labels=False)
    group_9_i = allparams_i.loc[allparams_i['QUINTILE'] == 9]
    group_9_i_beta = group_9_i['LAGRET'].mean()   #b1
    group_9_i_intercept = group_9_i['Intercept'].mean()  #b0
    group_9_i_etf_list = group_9_i.index.to_list()
    list_date_test_i = list_date[i+100:i+120]
    test_data_i = reg_data[reg_data['DATE'].isin(list_date_test_i) & reg_data['PERMNO'].isin(group_9_i_etf_list) ]
    df_reg_test_i = test_data_i.groupby('DATE').agg('mean')
    test_reg_result_i = regfun(df_reg_test_i, 'RET ~ LAGRET + MA5')
    group_9_i_test_beta_1 = test_reg_result_i['LAGRET']  # a1
    group_9_i_test_beta_2 = test_reg_result_i['MA5']     # a2
    group_9_i_test_intercept = test_reg_result_i['Intercept']  #a0
    current_date = list_date[i+120]
    df_compare_beta_high = df_compare_beta_high.append({'Current_Date' : current_date, 'beta_RET_1_100' : group_9_i_beta, 
                                              'intercept_1_100' : group_9_i_intercept, 'beta_RET_101_120' : group_9_i_test_beta_1,
                                              'beta_MA5_101_120' : group_9_i_test_beta_2, 'intercept_101_120' : group_9_i_test_intercept}, 
                ignore_index = True)

df_compare_beta_high 

Current_Date  beta_RET_1_100  intercept_1_100  beta_RET_101_120  \
0     2011-07-01        0.178490         0.000409         -0.178873   
1     2011-08-01        0.151959         0.000129         -0.024657   
2     2011-08-29        0.146737        -0.000041         -0.325565   
3     2011-09-27        0.076568        -0.000730          0.576658   
4     2011-10-25        0.117509        -0.001453         -0.089534   
..           ...             ...              ...               ...   
134   2022-02-24        0.151592        -0.000422          0.226214   
135   2022-03-24        0.180721        -0.000092          0.010196   
136   2022-04-22        0.189080        -0.000442         -0.157315   
137   2022-05-20        0.165537        -0.000248          0.031453   
138   2022-06-21        0.133128        -0.000708          0.001105   

     beta_MA5_101_120  intercept_101_120  
0            0.634430           0.000742  
1           -0.007095           0.000028  
2           -0.259415          -0.005717  
3           -0.518846          -0.002184  
4           -0.079046           0.003904  
..                ...                ...  
134         -0.580790          -0.000441  
135          0.071779          -0.000105  
136         -0.188725          -0.000556  
137         -0.675892          -0.006061  
138          0.429401          -0.002249  

[139 rows x 6 columns]

In [47]:
df_compare_beta_high.describe()

beta_RET_1_100  intercept_1_100  beta_RET_101_120  beta_MA5_101_120  \
count      139.000000       139.000000        139.000000        139.000000   
mean         0.135804         0.000112         -0.007201         -0.358198   
std          0.057678         0.000532          0.217616          0.595842   
min          0.049816        -0.001453         -0.578569         -1.764202   
25%          0.094938        -0.000199         -0.141187         -0.710750   
50%          0.124756         0.000129          0.002328         -0.349715   
75%          0.160324         0.000404          0.134448          0.010775   
max          0.455456         0.001913          0.740857          1.587835   

       intercept_101_120  
count         139.000000  
mean            0.000281  
std             0.002232  
min            -0.008525  
25%            -0.000898  
50%             0.000233  
75%             0.001485  
max             0.009347

__t_test results of a1 and a2__

In [48]:
ttest_ind(df_compare_beta_high['beta_RET_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-0.3901393555205569, pvalue=0.696734419538644)

In [49]:
ttest_ind(df_compare_beta_high['beta_MA5_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-7.087608611427452, pvalue=1.141678049477752e-11)

<h3> Loop 3: Time demeaned method, strongest reversal group </h3>

In [50]:
df_compare_beta_demean = pd.DataFrame(columns= ['Current_Date', 'beta_RET_1_100',
                                         'intercept_1_100','beta_RET_101_120','beta_MA5_101_120','intercept_101_120'])

In [51]:
for i in range(0,len(list_date)-120,20):
    list_date_i = list_date[i:i+100]
    reg_data_i = reg_data[reg_data['DATE'].isin(list_date_i)]
    allparams_i = reg_data_i.groupby('PERMNO').apply(regfun, 'RET ~ LAGRET')
    allparams_i['QUINTILE'] = pd.qcut(allparams_i.LAGRET,10,labels=False)
    group_0_i = allparams_i.loc[allparams_i['QUINTILE'] == 0]
    group_0_i_beta = group_0_i['LAGRET'].mean()   #b1
    group_0_i_intercept = group_0_i['Intercept'].mean()  #b0
    group_0_i_etf_list = group_0_i.index.to_list()
    list_date_test_i = list_date[i+100:i+120]
    test_data_i = reg_data[reg_data['DATE'].isin(list_date_test_i) & reg_data['PERMNO'].isin(group_0_i_etf_list) ]
    df_reg_test_i = test_data_i.groupby('DATE').agg('mean')  # get the mean
    
    # merge individual data with market mean within the given date
    test_data_i_merge = test_data_i.set_index('DATE')
    test_data_i_merge[['RET_m','LAGRET_m','MA5_m']] = df_reg_test_i[['RET','LAGRET','MA5']]
    test_data_i_merge['RET_demean'] = test_data_i_merge['RET'] - test_data_i_merge['RET_m']
    test_data_i_merge['LAGRET_demean'] = test_data_i_merge['LAGRET'] - test_data_i_merge['LAGRET_m']
    test_data_i_merge['MA5_demean'] = test_data_i_merge['MA5'] - test_data_i_merge['MA5_m']
    test_merge_result_i = regfun(test_data_i_merge, 'RET_demean ~ LAGRET_demean + MA5_demean')
    
    
    group_0_i_test_beta_1 = test_merge_result_i['LAGRET_demean']  # a1
    group_0_i_test_beta_2 = test_merge_result_i['MA5_demean']     # a2
    group_0_i_test_intercept = test_merge_result_i['Intercept']  #a0
    current_date = list_date[i+120]
    df_compare_beta_demean = df_compare_beta_demean.append({'Current_Date' : current_date, 'beta_RET_1_100' : group_0_i_beta, 
                                              'intercept_1_100' : group_0_i_intercept, 'beta_RET_101_120' : group_0_i_test_beta_1,
                                              'beta_MA5_101_120' : group_0_i_test_beta_2, 'intercept_101_120' : group_0_i_test_intercept}, 
                ignore_index = True)

df_compare_beta_demean  

Current_Date  beta_RET_1_100  intercept_1_100  beta_RET_101_120  \
0     2011-07-01       -0.170041     3.352956e-04         -0.012796   
1     2011-08-01       -0.156056     1.460491e-04          0.065799   
2     2011-08-29       -0.130097     9.806446e-05         -0.288462   
3     2011-09-27       -0.372890    -1.028800e-03          0.309859   
4     2011-10-25       -0.306070    -1.239271e-03         -0.127293   
..           ...             ...              ...               ...   
134   2022-02-24       -0.180961    -6.361183e-04          0.353139   
135   2022-03-24       -0.144030     3.980642e-07          0.157031   
136   2022-04-22       -0.133236    -1.932585e-04          0.088622   
137   2022-05-20       -0.126537    -6.343583e-05          0.059379   
138   2022-06-21       -0.131713    -1.284184e-03          0.017062   

     beta_MA5_101_120  intercept_101_120  
0           -0.190774      -1.490778e-19  
1           -0.116054      -1.084202e-19  
2            0.124487       1.694066e-19  
3           -0.890112      -5.963112e-19  
4           -0.506185       1.355253e-19  
..                ...                ...  
134         -0.463520       2.439455e-19  
135         -0.219597       2.439455e-19  
136          0.141025       4.336809e-19  
137         -0.377344      -6.776264e-20  
138          0.198501      -1.490778e-19  

[139 rows x 6 columns]

In [52]:
df_compare_beta_demean.describe()

beta_RET_1_100  intercept_1_100  beta_RET_101_120  beta_MA5_101_120  \
count      139.000000       139.000000        139.000000        139.000000   
mean        -0.219058         0.000283         -0.031637         -0.067811   
std          0.065337         0.000599          0.155664          0.360409   
min         -0.479472        -0.001335         -0.453531         -1.564747   
25%         -0.243637        -0.000040         -0.126810         -0.262572   
50%         -0.208351         0.000311         -0.032730         -0.022252   
75%         -0.177606         0.000647          0.055847          0.153088   
max         -0.063211         0.002748          0.508250          0.856228   

       intercept_101_120  
count       1.390000e+02  
mean       -7.166264e-21  
std         1.650225e-19  
min        -5.963112e-19  
25%        -1.067262e-19  
50%         0.000000e+00  
75%         8.470329e-20  
max         4.336809e-19

__t_test results of a1 and a2__

In [53]:
ttest_ind(df_compare_beta_demean['beta_RET_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-2.3961510758164275, pvalue=0.017234175147274218)

In [54]:
ttest_ind(df_compare_beta_demean['beta_MA5_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-2.218255331969338, pvalue=0.02735138144614749)

<h3> Loop 4: Time demeaned method, weakest reversal group </h3>

In [55]:
df_compare_beta_demean_high = pd.DataFrame(columns= ['Current_Date', 'beta_RET_1_100',
                                         'intercept_1_100','beta_RET_101_120','beta_MA5_101_120','intercept_101_120'])

In [56]:
for i in range(0,len(list_date)-120,20):
    list_date_i = list_date[i:i+100]
    reg_data_i = reg_data[reg_data['DATE'].isin(list_date_i)]
    allparams_i = reg_data_i.groupby('PERMNO').apply(regfun, 'RET ~ LAGRET')
    allparams_i['QUINTILE'] = pd.qcut(allparams_i.LAGRET,10,labels=False)
    group_9_i = allparams_i.loc[allparams_i['QUINTILE'] == 9]  # 'quintile' == 9 means the highest beta group
    group_9_i_beta = group_9_i['LAGRET'].mean()   #b1
    group_9_i_intercept = group_9_i['Intercept'].mean()  #b0
    group_9_i_etf_list = group_9_i.index.to_list()
    list_date_test_i = list_date[i+100:i+120]
    test_data_i = reg_data[reg_data['DATE'].isin(list_date_test_i) & reg_data['PERMNO'].isin(group_9_i_etf_list) ]
    df_reg_test_i = test_data_i.groupby('DATE').agg('mean')  # get the mean
    
    # merge individual data with market mean within the given date
    test_data_i_merge = test_data_i.set_index('DATE')
    test_data_i_merge[['RET_m','LAGRET_m','MA5_m']] = df_reg_test_i[['RET','LAGRET','MA5']]
    test_data_i_merge['RET_demean'] = test_data_i_merge['RET'] - test_data_i_merge['RET_m']
    test_data_i_merge['LAGRET_demean'] = test_data_i_merge['LAGRET'] - test_data_i_merge['LAGRET_m']
    test_data_i_merge['MA5_demean'] = test_data_i_merge['MA5'] - test_data_i_merge['MA5_m']
    test_merge_result_i = regfun(test_data_i_merge, 'RET_demean ~ LAGRET_demean + MA5_demean')
    
    
    group_9_i_test_beta_1 = test_merge_result_i['LAGRET_demean']  # a1
    group_9_i_test_beta_2 = test_merge_result_i['MA5_demean']     # a2
    group_9_i_test_intercept = test_merge_result_i['Intercept']  #a0
    current_date = list_date[i+120]
    df_compare_beta_demean_high = df_compare_beta_demean_high.append({'Current_Date' : current_date, 'beta_RET_1_100' : group_9_i_beta, 
                                              'intercept_1_100' : group_9_i_intercept, 'beta_RET_101_120' : group_9_i_test_beta_1,
                                              'beta_MA5_101_120' : group_9_i_test_beta_2, 'intercept_101_120' : group_9_i_test_intercept}, 
                ignore_index = True)

df_compare_beta_demean_high  

Current_Date  beta_RET_1_100  intercept_1_100  beta_RET_101_120  \
0     2011-07-01        0.178490         0.000409          0.127838   
1     2011-08-01        0.151959         0.000129         -0.185035   
2     2011-08-29        0.146737        -0.000041         -0.178659   
3     2011-09-27        0.076568        -0.000730          0.310162   
4     2011-10-25        0.117509        -0.001453         -0.281540   
..           ...             ...              ...               ...   
134   2022-02-24        0.151592        -0.000422          0.235131   
135   2022-03-24        0.180721        -0.000092          0.019289   
136   2022-04-22        0.189080        -0.000442          0.045271   
137   2022-05-20        0.165537        -0.000248         -0.085699   
138   2022-06-21        0.133128        -0.000708          0.042650   

     beta_MA5_101_120  intercept_101_120  
0           -0.252917      -1.355253e-20  
1            0.345546       3.320369e-19  
2           -0.222071       1.355253e-19  
3           -0.476432      -3.252607e-19  
4           -0.058815       1.626303e-19  
..                ...                ...  
134         -0.071248       2.710505e-19  
135          0.501541      -8.037534e-05  
136         -0.139578       1.355253e-19  
137         -0.190591      -5.421011e-20  
138          0.317008      -1.897354e-19  

[139 rows x 6 columns]

In [57]:
df_compare_beta_demean_high.describe()

beta_RET_1_100  intercept_1_100  beta_RET_101_120  beta_MA5_101_120  \
count      139.000000       139.000000        139.000000        139.000000   
mean         0.135804         0.000112         -0.012335         -0.043662   
std          0.057678         0.000532          0.138750          0.299776   
min          0.049816        -0.001453         -0.549854         -0.947719   
25%          0.094938        -0.000199         -0.093365         -0.211301   
50%          0.124756         0.000129         -0.019640         -0.037461   
75%          0.160324         0.000404          0.078647          0.149499   
max          0.455456         0.001913          0.346385          0.911975   

       intercept_101_120  
count       1.390000e+02  
mean       -6.368696e-07  
std         6.833500e-06  
min        -8.037534e-05  
25%        -6.945670e-20  
50%         1.355253e-20  
75%         1.219727e-19  
max         1.138412e-18

__t_test results of a1 and a2__

In [58]:
ttest_ind(df_compare_beta_demean_high['beta_RET_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-1.0480982030519346, pvalue=0.2955103026361249)

In [59]:
ttest_ind(df_compare_beta_demean_high['beta_MA5_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-1.7171948561551007, pvalue=0.08706534821635843)

<h3> Loop 5: Time Fama method, strongest reversal group </h3>

In [60]:
df_compare_beta_fama = pd.DataFrame(columns= ['Current_Date', 'beta_RET_1_100',
                                         'intercept_1_100','beta_RET_101_120','beta_MA5_101_120','intercept_101_120'])

In [61]:
for i in range(0,len(list_date)-120,20):
    list_date_i = list_date[i:i+100]
    reg_data_i = reg_data[reg_data['DATE'].isin(list_date_i)]
    allparams_i = reg_data_i.groupby('PERMNO').apply(regfun, 'RET ~ LAGRET')
    allparams_i['QUINTILE'] = pd.qcut(allparams_i.LAGRET,10,labels=False)
    group_0_i = allparams_i.loc[allparams_i['QUINTILE'] == 0]
    group_0_i_beta = group_0_i['LAGRET'].mean()   #b1
    group_0_i_intercept = group_0_i['Intercept'].mean()  #b0
    group_0_i_etf_list = group_0_i.index.to_list()
    list_date_test_i = list_date[i+100:i+120]
    test_data_i = reg_data[reg_data['DATE'].isin(list_date_test_i) & reg_data['PERMNO'].isin(group_0_i_etf_list) ]
    # df_reg_test_i = test_data_i.groupby('DATE').agg('mean')  # get the mean
    
    # unique part for fama method
    beta_RET_list = []
    beta_MA5_list = []
    intercept_list = []
    for j in range(i+100,i+120):
        list_date_fama_j = list_date[j]
        test_data_fama_j = test_data_i.loc[test_data_i['DATE']==list_date_fama_j]
        test_fama_result = regfun(test_data_fama_j, 'RET ~ LAGRET + MA5')
        beta_RET_list.append(test_fama_result['LAGRET'])
        beta_MA5_list.append(test_fama_result['MA5'])
        intercept_list.append(test_fama_result['Intercept'])
        
    
    group_0_i_test_beta_1 = statistics.fmean(beta_RET_list)  # a1
    group_0_i_test_beta_2 = statistics.fmean(beta_MA5_list)     # a2
    group_0_i_test_intercept = statistics.fmean(intercept_list)  #a0
    current_date = list_date[i+120]
    df_compare_beta_fama = df_compare_beta_fama.append({'Current_Date' : current_date, 'beta_RET_1_100' : group_0_i_beta, 
                                              'intercept_1_100' : group_0_i_intercept, 'beta_RET_101_120' : group_0_i_test_beta_1,
                                              'beta_MA5_101_120' : group_0_i_test_beta_2, 'intercept_101_120' : group_0_i_test_intercept}, 
                ignore_index = True)

df_compare_beta_fama  

Current_Date  beta_RET_1_100  intercept_1_100  beta_RET_101_120  \
0     2011-07-01       -0.170041     3.352956e-04          0.023884   
1     2011-08-01       -0.156056     1.460491e-04         -0.061067   
2     2011-08-29       -0.130097     9.806446e-05          0.052428   
3     2011-09-27       -0.372890    -1.028800e-03          0.354815   
4     2011-10-25       -0.306070    -1.239271e-03         -0.218764   
..           ...             ...              ...               ...   
134   2022-02-24       -0.180961    -6.361183e-04          0.107923   
135   2022-03-24       -0.144030     3.980642e-07          0.117024   
136   2022-04-22       -0.133236    -1.932585e-04          0.103485   
137   2022-05-20       -0.126537    -6.343583e-05          0.177293   
138   2022-06-21       -0.131713    -1.284184e-03          0.064645   

     beta_MA5_101_120  intercept_101_120  
0           -0.380289          -0.000156  
1           -0.025285           0.000541  
2           -0.144443          -0.000934  
3           -1.089360           0.000042  
4           -0.395715           0.000999  
..                ...                ...  
134          0.236134           0.000179  
135         -0.371275           0.000032  
136          0.211027          -0.000108  
137         -0.416971          -0.001101  
138         -0.067360           0.000564  

[139 rows x 6 columns]

In [62]:
df_compare_beta_fama.describe()

beta_RET_1_100  intercept_1_100  beta_RET_101_120  beta_MA5_101_120  \
count      139.000000       139.000000        139.000000        139.000000   
mean        -0.219058         0.000283         -0.032740         -0.041248   
std          0.065337         0.000599          0.142976          0.331696   
min         -0.479472        -0.001335         -0.432842         -1.089360   
25%         -0.243637        -0.000040         -0.131432         -0.283818   
50%         -0.208351         0.000311         -0.040436         -0.053144   
75%         -0.177606         0.000647          0.064735          0.200138   
max         -0.063211         0.002748          0.385524          0.718311   

       intercept_101_120  
count         139.000000  
mean            0.000141  
std             0.000713  
min            -0.002234  
25%            -0.000234  
50%             0.000132  
75%             0.000580  
max             0.003143

__t_test results of a1 and a2__

In [63]:
ttest_ind(df_compare_beta_fama['beta_RET_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-2.6997833349399225, pvalue=0.007366919587811382)

In [64]:
ttest_ind(df_compare_beta_fama['beta_MA5_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-1.466115231264877, pvalue=0.14375526580600942)

<h3> Loop 6: Time Fama method, weakest reversal group </h3>

In [65]:
df_compare_beta_fama_high = pd.DataFrame(columns= ['Current_Date', 'beta_RET_1_100',
                                         'intercept_1_100','beta_RET_101_120','beta_MA5_101_120','intercept_101_120'])

In [66]:
for i in range(0,len(list_date)-120,20):
    list_date_i = list_date[i:i+100]
    reg_data_i = reg_data[reg_data['DATE'].isin(list_date_i)]
    allparams_i = reg_data_i.groupby('PERMNO').apply(regfun, 'RET ~ LAGRET')
    allparams_i['QUINTILE'] = pd.qcut(allparams_i.LAGRET,10,labels=False)
    group_9_i = allparams_i.loc[allparams_i['QUINTILE'] == 9]  # 'QUINTILE' == 9 means the group with highest beta
    group_9_i_beta = group_9_i['LAGRET'].mean()   #b1
    group_9_i_intercept = group_9_i['Intercept'].mean()  #b0
    group_9_i_etf_list = group_9_i.index.to_list()
    list_date_test_i = list_date[i+100:i+120]
    test_data_i = reg_data[reg_data['DATE'].isin(list_date_test_i) & reg_data['PERMNO'].isin(group_9_i_etf_list) ]
    # df_reg_test_i = test_data_i.groupby('DATE').agg('mean')  # get the mean
    
    # unique part for fama method
    beta_RET_list = []
    beta_MA5_list = []
    intercept_list = []
    for j in range(i+100,i+120):
        list_date_fama_j = list_date[j]
        test_data_fama_j = test_data_i.loc[test_data_i['DATE']==list_date_fama_j]
        test_fama_result = regfun(test_data_fama_j, 'RET ~ LAGRET + MA5')
        beta_RET_list.append(test_fama_result['LAGRET'])
        beta_MA5_list.append(test_fama_result['MA5'])
        intercept_list.append(test_fama_result['Intercept'])
        
    
    group_9_i_test_beta_1 = statistics.fmean(beta_RET_list)  # a1
    group_9_i_test_beta_2 = statistics.fmean(beta_MA5_list)     # a2
    group_9_i_test_intercept = statistics.fmean(intercept_list)  #a0
    current_date = list_date[i+120]
    df_compare_beta_fama_high = df_compare_beta_fama_high.append({'Current_Date' : current_date, 'beta_RET_1_100' : group_9_i_beta, 
                                              'intercept_1_100' : group_9_i_intercept, 'beta_RET_101_120' : group_9_i_test_beta_1,
                                              'beta_MA5_101_120' : group_9_i_test_beta_2, 'intercept_101_120' : group_9_i_test_intercept}, 
                ignore_index = True)

df_compare_beta_fama_high

Current_Date  beta_RET_1_100  intercept_1_100  beta_RET_101_120  \
0     2011-07-01        0.178490         0.000409          0.064248   
1     2011-08-01        0.151959         0.000129          0.015992   
2     2011-08-29        0.146737        -0.000041         -0.166066   
3     2011-09-27        0.076568        -0.000730          0.242307   
4     2011-10-25        0.117509        -0.001453         -0.316473   
..           ...             ...              ...               ...   
134   2022-02-24        0.151592        -0.000422          0.253007   
135   2022-03-24        0.180721        -0.000092          0.217926   
136   2022-04-22        0.189080        -0.000442          0.032669   
137   2022-05-20        0.165537        -0.000248          0.041120   
138   2022-06-21        0.133128        -0.000708          0.079679   

     beta_MA5_101_120  intercept_101_120  
0           -0.180430           0.001141  
1            0.270067           0.000333  
2            0.238776          -0.000640  
3           -0.351579          -0.000785  
4            0.204506          -0.000517  
..                ...                ...  
134          0.067980           0.000564  
135          0.011333           0.000581  
136         -0.228676          -0.000219  
137         -0.345622          -0.000681  
138          0.284977           0.000634  

[139 rows x 6 columns]

In [67]:
df_compare_beta_fama_high.describe()

beta_RET_1_100  intercept_1_100  beta_RET_101_120  beta_MA5_101_120  \
count      139.000000       139.000000        139.000000        139.000000   
mean         0.135804         0.000112         -0.010790          0.017020   
std          0.057678         0.000532          0.127086          0.292882   
min          0.049816        -0.001453         -0.316473         -0.767153   
25%          0.094938        -0.000199         -0.095017         -0.191739   
50%          0.124756         0.000129         -0.023679          0.041008   
75%          0.160324         0.000404          0.065207          0.228134   
max          0.455456         0.001913          0.330829          0.818061   

       intercept_101_120  
count         139.000000  
mean            0.000107  
std             0.001006  
min            -0.002547  
25%            -0.000457  
50%             0.000013  
75%             0.000739  
max             0.003462

__t_test results of a1 and a2__

In [68]:
ttest_ind(df_compare_beta_fama_high['beta_RET_101_120'], df_zeros['a'])

Ttest_indResult(statistic=-1.0010339209008798, pvalue=0.31768722488464296)

In [69]:
ttest_ind(df_compare_beta_fama_high['beta_MA5_101_120'], df_zeros['a'])

Ttest_indResult(statistic=0.6851314095375707, pvalue=0.49383599397689226)

<h2> Testing Results Summary </h2>

<h3> Coefficient T test tables </h3>

| Test Method | b_1(form a group) | a_1 | t_statistic(a_1) | p_value(a_1) | a_2 | t_statistic(a_2) | p_value(a_2) |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| portfolio_low | -0.219 | -0.0405 | __-2.002__ | 0.0463 | -0.3818 | __-6.621__ | <0.0001 |
| portfolio_high | 0.136 | -0.0072 | -0.390 | 0.696 | -0.3581 | __-7.088__ | <0.0001 |
| time_demean_low | -0.219 | -0.0316 | __-2.396__ | 0.0172 | -0.0678 | __-2.218__ | 0.0273 |
| time_demean_high | 0.136 | -0.0123 | -1.048 | 0.296 | -0.0437 | -1.717 | 0.087 |
| Fama_low | -0.219 | -0.0327 | __-2.699__ | 0.0073 | -0.0412 | -1.466 | 0.1437 |
| Fama_high | 0.136 | -0.0108 | -1.001 | 0.317 | 0.0170 | 0.685 | 0.493 |

<h3> Analysis </h3>

From the table above, it shows that there exist a statistical significant effect on the consistency of reversal for etfs in the group of lowest b1.  
- For the etf with the strongest reversal effect by past data, all 3 regression method provide significant t statistics.
- For the etf with the weakest reversal effect by past data, the portfolio method provide high t statistics for the coefficient of MA(5)
- MA(5) is an important factor for a portfolio (no matter whether it has past strong reversal)
- except for MA(5) in Fama_low, all other regression coefficients are significant for the group with strongest reversal
- return on the previous day could be a reasonable predictor for the next day within the group with historically strong reversal
- the high and low group clearly have different characteristic in future return performance, so the grouping by past b1 is effective

<h2> Portfolio by reversal strategy </h2>

According to the previous analysis, we can build a portfolio as follows:
- since the group with strongest reversal has significant reversal effect for future returns, we focus on group 0 (strongest reversal)
- There are 55 etfs in group 0
- According to the return of previous day, group them into 5 category (Q0:lowest ret; Q4:highest ret)
- __Strategy: Long the etfs in Q0 and short the assets in Q4__
- if reversal do exist, we can earn money from this strategy


In [94]:
port_return_list = []  # this is the return list for the portfolio given above

for i in range(0,len(list_date)-120,20):
    list_date_i = list_date[i:i+100]
    reg_data_i = reg_data[reg_data['DATE'].isin(list_date_i)]
    allparams_i = reg_data_i.groupby('PERMNO').apply(regfun, 'RET ~ LAGRET')
    allparams_i['QUINTILE'] = pd.qcut(allparams_i.LAGRET,10,labels=False)
    group_0_i = allparams_i.loc[allparams_i['QUINTILE'] == 0]
    group_0_i_beta = group_0_i['LAGRET'].mean()   #b1
    group_0_i_intercept = group_0_i['Intercept'].mean()  #b0
    group_0_i_etf_list = group_0_i.index.to_list()
    list_date_test_i = list_date[i+100:i+120]
    test_data_i = reg_data[reg_data['DATE'].isin(list_date_test_i) & reg_data['PERMNO'].isin(group_0_i_etf_list) ]
    
    for j in range(i+100,i+120):
        list_date_test_j = list_date[j]
        test_data_j = test_data_i.loc[test_data_i['DATE']==list_date_test_j]
        test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
        agg_result = test_data_j.groupby('QUINTILE').agg('mean')
        port_return = agg_result.loc[0,'RET'] - agg_result.loc[4,'RET']
        port_return_list.append(port_return)

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data_j['QUINTILE'] = pd.qcut(test_data_j.LAGRET,5,labels=False)
<ipython-input-94-0285fa0e2fcd>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the do

In [96]:
len(port_return_list) # equals to 20 * 139 (in total update the group for 139 times, each group lasts for 20 days)

2780

get statistics for the portfolio

In [97]:
mean_port = statistics.fmean(port_return_list)
mean_port

0.0011819851810903133

In [98]:
std_port = statistics.stdev(port_return_list)
std_port

0.024577769059128975

In [99]:
t_port = np.sqrt(len(port_return_list)) * mean_port / std_port
t_port

2.5356655514227393

In [102]:
import scipy.stats

#find p-value for one side t test
scipy.stats.t.sf(abs(t_port), df=len(port_return_list))

0.005638864319350484

In [136]:
Sharpe_port = mean_port / std_port
Sharpe_port

0.04809163835198809

<h3> Portfolio Performance Summary </h3>

- The portfolio has significant t statistics: t_statistic = 2.536; p_value = 0.0056
- The portfolio provides a mean return of 0.0012; the return std is 0.0246
- The Sharpe Ratio is given by 0.0481

__In general, the portfolio shows that reversal do have consistency, and we can earn profit from it.__

<h1> Study on reversal in ETFs with different market capitalization</h1>

Study the reversal performance between small cap and large cap: 

On each day, the 548 etfs are divided into 4 groups according to their market cap, from 1 being the smallest market cap to 4 being the largest market cap, and each geoup will contain 137 etfs. Fama Macbech regression will then be run on these 137 etfs by regressing returns on lagged returns. Each group will get coefficients based on the 2892 days. These coefficients are sample estimates for the true reversal effect, so t test is conducted to validate the significance for coefficients.

__Null hypothesis: Large Market cap (top 25%) and Small Market cap (bottom 25%) ETFs have the same reversal effect.__

__Alternative hypothesis: Large Market cap (top 25%) has a smaller reversal effect than the Small Market cap ETFs (bottom 25%).__

<h2> Further Data Cleaning </h2>

We can see that the period most etfs co-existed is in these 2893 days and there are 550 ETFs contain data of 2893 days. That's the reason why we chose 2893 as we want to include as many ETFs as we can.

In [70]:
t = pd.DataFrame(data_2011.groupby('PERMNO')['DATE'].count())
t = t.reset_index()
t = t.set_index(["DATE"])
t.groupby("DATE")["PERMNO"].count().sort_values()

DATE
507       1
638       1
640       1
1576      1
1574      1
       ... 
184      19
1066     29
1828     33
2894     69
2893    550
Name: PERMNO, Length: 1379, dtype: int64

In [74]:
list_permno = permno.index.tolist()
len(list_permno)

550

dt_etfs: this is the dataframe for the 550 etfs that existed for 2893 days.

In [75]:
df_etfs = data_2011[data_2011['PERMNO'].isin(list_permno)]
df_etfs.head()

PERMNO       DATE                  COMNAM   TICKER  SHRCD   SICCD  \
85861  10113.0 2011-01-03  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   
85862  10113.0 2011-01-04  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   
85863  10113.0 2011-01-05  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   
85864  10113.0 2011-01-06  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   
85865  10113.0 2011-01-07  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   

          PRC      VOL    OPENPRC      ASKHI      BIDLO        BID        ASK  \
85861  30.063   1600.0  29.980000  30.063000  29.879999  29.969999  30.030001   
85862  30.010  22200.0  30.299999  30.350000  29.910000  29.969999  30.059999   
85863  29.830  14000.0  29.841999  29.898001  29.800100  29.830000  29.910000   
85864  29.830  13200.0  29.820000  29.850000  29.740000  29.820000  29.920000   
85865  29.670   1600.0  29.740000  29.740000  29.670000  29.660000  29.719999   

            RET      RETX  SHROUT  DIVAMT  
85861  0.007473  0.007473   275.0     NaN  
85862 -0.001763 -0.001763   275.0     NaN  
85863 -0.005998 -0.005998   275.0     NaN  
85864  0.000000  0.000000   275.0     NaN  
85865 -0.005364 -0.005364   275.0     NaN

Checking for PERMNO which has NA values; 91934 and 93378 have some NA values in ret and they need to be excluded.

In [76]:
df_etfs["PERMNO"].loc[df_etfs.isna().loc[:,"RET"]]

38346204    91934.0
38346205    91934.0
38346206    91934.0
38346207    91934.0
38346208    91934.0
             ...   
38346281    91934.0
38346282    91934.0
38346283    91934.0
38346284    91934.0
41235851    93378.0
Name: PERMNO, Length: 82, dtype: float64

In [77]:
df_etfs["PERMNO"].loc[df_etfs.isna().loc[:,"PRC"]].unique()

array([91934., 93378.])

In [78]:
list_permno.remove(91934.0)
list_permno.remove(93378.0)

In [81]:
df_etfs = data_2011[data_2011['PERMNO'].isin(list_permno)]
df_etfs.head()

PERMNO       DATE                  COMNAM   TICKER  SHRCD   SICCD  \
85861  10113.0 2011-01-03  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   
85862  10113.0 2011-01-04  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   
85863  10113.0 2011-01-05  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   
85864  10113.0 2011-01-06  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   
85865  10113.0 2011-01-07  b'ADVISORSHARES TRUST'  b'AADR'   73.0  6726.0   

          PRC      VOL    OPENPRC      ASKHI      BIDLO        BID        ASK  \
85861  30.063   1600.0  29.980000  30.063000  29.879999  29.969999  30.030001   
85862  30.010  22200.0  30.299999  30.350000  29.910000  29.969999  30.059999   
85863  29.830  14000.0  29.841999  29.898001  29.800100  29.830000  29.910000   
85864  29.830  13200.0  29.820000  29.850000  29.740000  29.820000  29.920000   
85865  29.670   1600.0  29.740000  29.740000  29.670000  29.660000  29.719999   

            RET      RETX  SHROUT  DIVAMT  
85861  0.007473  0.007473   275.0     NaN  
85862 -0.001763 -0.001763   275.0     NaN  
85863 -0.005998 -0.005998   275.0     NaN  
85864  0.000000  0.000000   275.0     NaN  
85865 -0.005364 -0.005364   275.0     NaN

In [87]:
df_etfs = df_etfs.drop(columns=['COMNAM','SICCD','OPENPRC','BID','ASK','RETX','DIVAMT','SHRCD'])

Checking whether these permnos are trufully contemporaneous:
    All ETFs started in 2011-01-03 and ended in 2022-06-30 and all have 2893 data. They should be contempraneous without NAs now.

In [88]:
df_etfs.groupby("PERMNO")["DATE"].head(1).unique()

array(['2011-01-03T00:00:00.000000000'], dtype='datetime64[ns]')

In [89]:
df_etfs.groupby("PERMNO")["DATE"].tail(1).unique()

array(['2022-06-30T00:00:00.000000000'], dtype='datetime64[ns]')

In [90]:
df_etfs.index = range(len(df_etfs))
df_etfs

PERMNO       DATE   TICKER     PRC       VOL      ASKHI      BIDLO  \
0        10113.0 2011-01-03  b'AADR'  30.063    1600.0  30.063000  29.879999   
1        10113.0 2011-01-04  b'AADR'  30.010   22200.0  30.350000  29.910000   
2        10113.0 2011-01-05  b'AADR'  29.830   14000.0  29.898001  29.800100   
3        10113.0 2011-01-06  b'AADR'  29.830   13200.0  29.850000  29.740000   
4        10113.0 2011-01-07  b'AADR'  29.670    1600.0  29.740000  29.670000   
...          ...        ...      ...     ...       ...        ...        ...   
1585359  93379.0 2022-06-24  b'EPOL'  14.570  106848.0  14.640000  14.360000   
1585360  93379.0 2022-06-27  b'EPOL'  14.760  140237.0  14.880000  14.690500   
1585361  93379.0 2022-06-28  b'EPOL'  14.700  166483.0  15.060000  14.585000   
1585362  93379.0 2022-06-29  b'EPOL'  14.740   55073.0  14.870000  14.660000   
1585363  93379.0 2022-06-30  b'EPOL'  14.630   66227.0  14.690000  14.340000   

              RET   SHROUT  
0        0.007473    275.0  
1       -0.001763    275.0  
2       -0.005998    275.0  
3        0.000000    275.0  
4       -0.005364    275.0  
...           ...      ...  
1585359  0.027503  11600.0  
1585360  0.013041  11600.0  
1585361 -0.004065  11600.0  
1585362  0.002721  11600.0  
1585363 -0.007463  10700.0  

[1585364 rows x 9 columns]

In [91]:
etf_clean = df_etfs.set_index(['PERMNO','DATE'])
etf_clean

TICKER     PRC       VOL      ASKHI      BIDLO       RET  \
PERMNO  DATE                                                                    
10113.0 2011-01-03  b'AADR'  30.063    1600.0  30.063000  29.879999  0.007473   
        2011-01-04  b'AADR'  30.010   22200.0  30.350000  29.910000 -0.001763   
        2011-01-05  b'AADR'  29.830   14000.0  29.898001  29.800100 -0.005998   
        2011-01-06  b'AADR'  29.830   13200.0  29.850000  29.740000  0.000000   
        2011-01-07  b'AADR'  29.670    1600.0  29.740000  29.670000 -0.005364   
...                     ...     ...       ...        ...        ...       ...   
93379.0 2022-06-24  b'EPOL'  14.570  106848.0  14.640000  14.360000  0.027503   
        2022-06-27  b'EPOL'  14.760  140237.0  14.880000  14.690500  0.013041   
        2022-06-28  b'EPOL'  14.700  166483.0  15.060000  14.585000 -0.004065   
        2022-06-29  b'EPOL'  14.740   55073.0  14.870000  14.660000  0.002721   
        2022-06-30  b'EPOL'  14.630   66227.0  14.690000  14.340000 -0.007463   

                     SHROUT  
PERMNO  DATE                 
10113.0 2011-01-03    275.0  
        2011-01-04    275.0  
        2011-01-05    275.0  
        2011-01-06    275.0  
        2011-01-07    275.0  
...                     ...  
93379.0 2022-06-24  11600.0  
        2022-06-27  11600.0  
        2022-06-28  11600.0  
        2022-06-29  11600.0  
        2022-06-30  10700.0  

[1585364 rows x 7 columns]

In [92]:
etf_clean["LAGR"] = etf_clean["RET"].groupby("PERMNO").shift()
etf_clean = etf_clean.reorder_levels(["DATE","PERMNO"])
etf_clean = etf_clean.sort_index()
etf_clean=etf_clean.dropna()
etf_clean

TICKER         PRC        VOL       ASKHI       BIDLO  \
DATE       PERMNO                                                            
2011-01-04 10113.0  b'AADR'   30.010000    22200.0   30.350000   29.910000   
           11264.0  b'RETL'  -57.290001        0.0   57.340000   57.240002   
           11407.0   b'LIT'   23.040001   387600.0   23.790001   22.860001   
           11996.0  b'EMLC'   26.650000   202500.0   26.770000   26.580000   
           12035.0  b'AMLP'   16.070000  1089700.0   16.150000   16.023600   
...                     ...         ...        ...         ...         ...   
2022-06-30 93366.0  b'PSCH'  136.839996     5090.0  138.810303  136.240005   
           93367.0  b'PSCD'   74.748596     1299.0   75.150002   74.610001   
           93376.0  b'EUSA'   70.639999    21891.0   71.074997   69.839996   
           93377.0  b'EIDO'   22.379999   683100.0   22.385000   22.100000   
           93379.0  b'EPOL'   14.630000    66227.0   14.690000   14.340000   

                         RET   SHROUT      LAGR  
DATE       PERMNO                                
2011-01-04 10113.0 -0.001763    275.0  0.007473  
           11264.0 -0.021876    100.0  0.020051  
           11407.0 -0.024142   6200.0  0.038259  
           11996.0  0.003011    200.0 -0.003301  
           12035.0 -0.003102  35150.0  0.003111  
...                      ...      ...       ...  
2022-06-30 93366.0 -0.015398   2410.0  0.004191  
           93367.0 -0.016505    340.0 -0.017668  
           93376.0 -0.007586   5550.0 -0.006005  
           93377.0 -0.001339  19500.0 -0.013644  
           93379.0 -0.007463  10700.0  0.002721  

[1584816 rows x 8 columns]

Each date (for 2892 days) consist of exactly 548 ETF data.

In [103]:
test_etf_count = etf_clean.reset_index(["PERMNO"]).groupby('DATE').count()
test_etf_count

PERMNO  TICKER  PRC  VOL  ASKHI  BIDLO  RET  SHROUT  LAGR
DATE                                                                 
2011-01-04     548     548  548  548    548    548  548     548   548
2011-01-05     548     548  548  548    548    548  548     548   548
2011-01-06     548     548  548  548    548    548  548     548   548
2011-01-07     548     548  548  548    548    548  548     548   548
2011-01-10     548     548  548  548    548    548  548     548   548
...            ...     ...  ...  ...    ...    ...  ...     ...   ...
2022-06-24     548     548  548  548    548    548  548     548   548
2022-06-27     548     548  548  548    548    548  548     548   548
2022-06-28     548     548  548  548    548    548  548     548   548
2022-06-29     548     548  548  548    548    548  548     548   548
2022-06-30     548     548  548  548    548    548  548     548   548

[2892 rows x 9 columns]

<h2> Reversal by Daily Returns </h2>

<h3> First the daily returns and reversal by day are examined.</h3>

In [104]:
etf_clean["MKTCAP"] = etf_clean["SHROUT"]*abs(etf_clean["PRC"])

In [105]:
etf_clean.head()

TICKER        PRC        VOL      ASKHI      BIDLO  \
DATE       PERMNO                                                         
2011-01-04 10113.0  b'AADR'  30.010000    22200.0  30.350000  29.910000   
           11264.0  b'RETL' -57.290001        0.0  57.340000  57.240002   
           11407.0   b'LIT'  23.040001   387600.0  23.790001  22.860001   
           11996.0  b'EMLC'  26.650000   202500.0  26.770000  26.580000   
           12035.0  b'AMLP'  16.070000  1089700.0  16.150000  16.023600   

                         RET   SHROUT      LAGR         MKTCAP  
DATE       PERMNO                                               
2011-01-04 10113.0 -0.001763    275.0  0.007473    8252.750063  
           11264.0 -0.021876    100.0  0.020051    5729.000092  
           11407.0 -0.024142   6200.0  0.038259  142848.005676  
           11996.0  0.003011    200.0 -0.003301    5329.999924  
           12035.0 -0.003102  35150.0  0.003111  564860.489273

In [106]:
def quintiles(inser):
    outser = pd.qcut(inser, q=4, labels=range(1,5))
    return outser

In [107]:
def regfun(df):
    results = smf.ols('RET ~ LAGR', data=df).fit()
    return results.params

<h3> Divide ETFs into 4 groups according to their market cap in each date for 2892 days </h3>

In [108]:
etf_clean["Quintile"] = etf_clean["MKTCAP"].groupby("DATE").apply(quintiles)
etf_clean.head()

TICKER        PRC        VOL      ASKHI      BIDLO  \
DATE       PERMNO                                                         
2011-01-04 10113.0  b'AADR'  30.010000    22200.0  30.350000  29.910000   
           11264.0  b'RETL' -57.290001        0.0  57.340000  57.240002   
           11407.0   b'LIT'  23.040001   387600.0  23.790001  22.860001   
           11996.0  b'EMLC'  26.650000   202500.0  26.770000  26.580000   
           12035.0  b'AMLP'  16.070000  1089700.0  16.150000  16.023600   

                         RET   SHROUT      LAGR         MKTCAP Quintile  
DATE       PERMNO                                                        
2011-01-04 10113.0 -0.001763    275.0  0.007473    8252.750063        1  
           11264.0 -0.021876    100.0  0.020051    5729.000092        1  
           11407.0 -0.024142   6200.0  0.038259  142848.005676        2  
           11996.0  0.003011    200.0 -0.003301    5329.999924        1  
           12035.0 -0.003102  35150.0  0.003111  564860.489273        3

<h3> Run Fama Macbecth Regression on these 4 groups in each date. </h3>

So there will be 2892 slope coeffcieints for each group. And 2892 x 4 = 11668 rows.

In [109]:
mktcap_params=etf_clean.groupby(["Quintile","DATE"]).apply(regfun)
mktcap_params

Intercept      LAGR
Quintile DATE                           
1        2011-01-04  -0.002082 -0.295699
         2011-01-05  -0.001282 -0.100838
         2011-01-06  -0.004015  0.119495
         2011-01-07  -0.001736  0.203594
         2011-01-10   0.000777  0.334257
...                        ...       ...
4        2022-06-24   0.024647  0.185801
         2022-06-27   0.002410 -0.122753
         2022-06-28  -0.011941  1.190459
         2022-06-29  -0.005730 -0.153390
         2022-06-30  -0.005241  0.368262

[11568 rows x 2 columns]

<h3> Results </h3>

There is no clean pattern in coeffiencts between groups.

In [110]:
param_stats=mktcap_params.loc[:,"LAGR"].groupby("Quintile").describe()
param_stats

count      mean       std       min       25%       50%       75%  \
Quintile                                                                       
1         2892.0 -0.021546  0.530077 -2.651687 -0.332270 -0.039174  0.266762   
2         2892.0 -0.005475  0.526414 -2.978817 -0.301091 -0.017824  0.285569   
3         2892.0 -0.013571  0.537687 -2.568632 -0.320061 -0.024627  0.274496   
4         2892.0 -0.005685  0.475742 -3.033819 -0.268986 -0.011293  0.252917   

               max  
Quintile            
1         3.125090  
2         2.951054  
3         2.682705  
4         2.692930

When we only look at the largest market cap group, the average slope coefficient is -0.005685, meaning there is a small reversal effect. However, the result is not statistically significant as the t-stats is -0.6426.

In [111]:
highcap_stats = param_stats.loc[4,]
tstats_high=highcap_stats.loc["mean"]/(highcap_stats.loc["std"]/np.sqrt(highcap_stats.loc["count"]))
highcap_stats.loc["tstats"] = tstats_high
highcap_stats

count     2892.000000
mean        -0.005685
std          0.475742
min         -3.033819
25%         -0.268986
50%         -0.011293
75%          0.252917
max          2.692930
tstats      -0.642602
Name: 4, dtype: float64

When we only look at the smallest market cap group, the average slope coefficient or estimated daily coeffcient is -0.021546, meaning there is a reversal effect. And the result is statistically significant as the t-stats is -2.1858.

In [112]:
smallcap_stats=param_stats.loc[1,]
tstats_small = smallcap_stats.loc["mean"]/(smallcap_stats.loc["std"]/np.sqrt(smallcap_stats.loc["count"]))
smallcap_stats.loc["tstats"]=tstats_small
smallcap_stats

count     2892.000000
mean        -0.021546
std          0.530077
min         -2.651687
25%         -0.332270
50%         -0.039174
75%          0.266762
max          3.125090
tstats      -2.185840
Name: 1, dtype: float64

When we only look at the 3rd quartile market cap group, the result is statistically insignificant as the t-stats is -1.357.

In [113]:
highmid_stats = param_stats.loc[3,]
tstats_highmid = highmid_stats.loc["mean"]/(highmid_stats.loc["std"]/np.sqrt(highmid_stats.loc["count"]))
highmid_stats.loc["tstats"]=tstats_highmid
highmid_stats

count     2892.000000
mean        -0.013571
std          0.537687
min         -2.568632
25%         -0.320061
50%         -0.024627
75%          0.274496
max          2.682705
tstats      -1.357350
Name: 3, dtype: float64

When we only look at the 2nd quartile market cap group, the result is statistically insignificant as the t-stats is -0.559.

In [114]:
lowmid_stats = param_stats.loc[2,]
tstats_lowmid = lowmid_stats .loc["mean"]/(lowmid_stats .loc["std"]/np.sqrt(lowmid_stats .loc["count"]))
lowmid_stats.loc["tstats"]=tstats_lowmid
lowmid_stats

count     2892.000000
mean        -0.005475
std          0.526414
min         -2.978817
25%         -0.301091
50%         -0.017824
75%          0.285569
max          2.951054
tstats      -0.559276
Name: 2, dtype: float64

So it seems like only the smallest cap has a significant reversal effect. The difference in effect between groups is also worth to look at.

<h3> Test difference between group 1 and group 4 </h3>

When we only look at the difference between smallest and lagest market cap group, the difference in average slope coefficients or estimated daily coeffcients is -0.015861, and the result is statistically significant as the t-stats is -2.467833 < -1.96 (2 sided t test) < -1.645 (1 sided t test), meaning the smallest cap group has a larger reversal effect than the larget cap group.

In [115]:
mktcap_diff = mktcap_params.loc[1,"LAGR"] - mktcap_params.loc[4,"LAGR"] 
smallminuslarge_stats=mktcap_diff.describe()
tstats_diff = smallminuslarge_stats.loc["mean"]/(smallminuslarge_stats.loc["std"]/np.sqrt(smallminuslarge_stats.loc["count"]))
smallminuslarge_stats.loc["tstats"]=tstats_diff
smallminuslarge_stats

count     2892.000000
mean        -0.015861
std          0.345628
min         -2.129561
25%         -0.192360
50%         -0.010312
75%          0.167107
max          1.967936
tstats      -2.467833
Name: LAGR, dtype: float64

<h2> Reversal by Weekly Returns </h2>

Next, a longer horizon reversal - Weekly reversal is examined. Does the reversal effect in small cap still exist when a longer time horizon applies? The difference from the daily reversal is weekly returns and weekly lagged returns are used here.

<h3> Create a DF for weekly data from daily data </h3>

In [116]:
df_etfs.set_index(["DATE"])

PERMNO   TICKER     PRC       VOL      ASKHI      BIDLO  \
DATE                                                                   
2011-01-03  10113.0  b'AADR'  30.063    1600.0  30.063000  29.879999   
2011-01-04  10113.0  b'AADR'  30.010   22200.0  30.350000  29.910000   
2011-01-05  10113.0  b'AADR'  29.830   14000.0  29.898001  29.800100   
2011-01-06  10113.0  b'AADR'  29.830   13200.0  29.850000  29.740000   
2011-01-07  10113.0  b'AADR'  29.670    1600.0  29.740000  29.670000   
...             ...      ...     ...       ...        ...        ...   
2022-06-24  93379.0  b'EPOL'  14.570  106848.0  14.640000  14.360000   
2022-06-27  93379.0  b'EPOL'  14.760  140237.0  14.880000  14.690500   
2022-06-28  93379.0  b'EPOL'  14.700  166483.0  15.060000  14.585000   
2022-06-29  93379.0  b'EPOL'  14.740   55073.0  14.870000  14.660000   
2022-06-30  93379.0  b'EPOL'  14.630   66227.0  14.690000  14.340000   

                 RET   SHROUT  
DATE                           
2011-01-03  0.007473    275.0  
2011-01-04 -0.001763    275.0  
2011-01-05 -0.005998    275.0  
2011-01-06  0.000000    275.0  
2011-01-07 -0.005364    275.0  
...              ...      ...  
2022-06-24  0.027503  11600.0  
2022-06-27  0.013041  11600.0  
2022-06-28 -0.004065  11600.0  
2022-06-29  0.002721  11600.0  
2022-06-30 -0.007463  10700.0  

[1585364 rows x 8 columns]

In [117]:
df_etfs["DOW"]=df_etfs.set_index(["DATE"]).index.dayofweek
df_etfs=df_etfs.set_index(["PERMNO","DATE"])

In [118]:
df_etfs.groupby("PERMNO")["DOW"].pct_change()<0

PERMNO   DATE      
10113.0  2011-01-03    False
         2011-01-04    False
         2011-01-05    False
         2011-01-06    False
         2011-01-07    False
                       ...  
93379.0  2022-06-24    False
         2022-06-27     True
         2022-06-28    False
         2022-06-29    False
         2022-06-30    False
Name: DOW, Length: 1585364, dtype: bool

In [119]:
dfw_etfs=df_etfs.loc[df_etfs.groupby("PERMNO")["DOW"].pct_change()<0]
dfw_etfs=dfw_etfs.drop(columns = ["RET"])
dfw_etfs

TICKER        PRC       VOL      ASKHI      BIDLO  \
PERMNO  DATE                                                             
10113.0 2011-01-10  b'AADR'  29.648001   33100.0  29.648001  29.370001   
        2011-01-18  b'AADR'  30.200001    1700.0  30.290001  30.190100   
        2011-01-24  b'AADR' -30.070000       0.0  30.120001  30.020000   
        2011-01-31  b'AADR'  29.836000     700.0  29.860001  29.836000   
        2011-02-07  b'AADR'  30.398600     700.0  30.398600  30.290001   
...                     ...        ...       ...        ...        ...   
93379.0 2022-05-31  b'EPOL'  16.510000  128352.0  16.750000  16.500000   
        2022-06-06  b'EPOL'  16.350000  591015.0  16.620001  16.271999   
        2022-06-13  b'EPOL'  14.410000  279888.0  14.560000  14.340000   
        2022-06-21  b'EPOL'  14.890000  126062.0  15.110000  14.860000   
        2022-06-27  b'EPOL'  14.760000  140237.0  14.880000  14.690500   

                     SHROUT  DOW  
PERMNO  DATE                      
10113.0 2011-01-10    275.0    0  
        2011-01-18    275.0    1  
        2011-01-24    275.0    0  
        2011-01-31    275.0    0  
        2011-02-07    275.0    0  
...                     ...  ...  
93379.0 2022-05-31  11600.0    1  
        2022-06-06  11600.0    0  
        2022-06-13  11600.0    0  
        2022-06-21  11600.0    1  
        2022-06-27  11600.0    0  

[328252 rows x 7 columns]

In [120]:
dfw_etfs["ABS PRC"] = abs(dfw_etfs["PRC"])
dfw_etfs["RET"]=dfw_etfs.groupby("PERMNO")["ABS PRC"].pct_change()
dfw_etfs #weekly returns

TICKER        PRC       VOL      ASKHI      BIDLO  \
PERMNO  DATE                                                             
10113.0 2011-01-10  b'AADR'  29.648001   33100.0  29.648001  29.370001   
        2011-01-18  b'AADR'  30.200001    1700.0  30.290001  30.190100   
        2011-01-24  b'AADR' -30.070000       0.0  30.120001  30.020000   
        2011-01-31  b'AADR'  29.836000     700.0  29.860001  29.836000   
        2011-02-07  b'AADR'  30.398600     700.0  30.398600  30.290001   
...                     ...        ...       ...        ...        ...   
93379.0 2022-05-31  b'EPOL'  16.510000  128352.0  16.750000  16.500000   
        2022-06-06  b'EPOL'  16.350000  591015.0  16.620001  16.271999   
        2022-06-13  b'EPOL'  14.410000  279888.0  14.560000  14.340000   
        2022-06-21  b'EPOL'  14.890000  126062.0  15.110000  14.860000   
        2022-06-27  b'EPOL'  14.760000  140237.0  14.880000  14.690500   

                     SHROUT  DOW    ABS PRC       RET  
PERMNO  DATE                                           
10113.0 2011-01-10    275.0    0  29.648001       NaN  
        2011-01-18    275.0    1  30.200001  0.018618  
        2011-01-24    275.0    0  30.070000 -0.004305  
        2011-01-31    275.0    0  29.836000 -0.007782  
        2011-02-07    275.0    0  30.398600  0.018856  
...                     ...  ...        ...       ...  
93379.0 2022-05-31  11600.0    1  16.510000  0.013505  
        2022-06-06  11600.0    0  16.350000 -0.009691  
        2022-06-13  11600.0    0  14.410000 -0.118654  
        2022-06-21  11600.0    1  14.890000  0.033310  
        2022-06-27  11600.0    0  14.760000 -0.008731  

[328252 rows x 9 columns]

In [121]:
dfw_etfs["LAGR"]=dfw_etfs.groupby("PERMNO")["RET"].shift()
dfw_etfs

TICKER        PRC       VOL      ASKHI      BIDLO  \
PERMNO  DATE                                                             
10113.0 2011-01-10  b'AADR'  29.648001   33100.0  29.648001  29.370001   
        2011-01-18  b'AADR'  30.200001    1700.0  30.290001  30.190100   
        2011-01-24  b'AADR' -30.070000       0.0  30.120001  30.020000   
        2011-01-31  b'AADR'  29.836000     700.0  29.860001  29.836000   
        2011-02-07  b'AADR'  30.398600     700.0  30.398600  30.290001   
...                     ...        ...       ...        ...        ...   
93379.0 2022-05-31  b'EPOL'  16.510000  128352.0  16.750000  16.500000   
        2022-06-06  b'EPOL'  16.350000  591015.0  16.620001  16.271999   
        2022-06-13  b'EPOL'  14.410000  279888.0  14.560000  14.340000   
        2022-06-21  b'EPOL'  14.890000  126062.0  15.110000  14.860000   
        2022-06-27  b'EPOL'  14.760000  140237.0  14.880000  14.690500   

                     SHROUT  DOW    ABS PRC       RET      LAGR  
PERMNO  DATE                                                     
10113.0 2011-01-10    275.0    0  29.648001       NaN       NaN  
        2011-01-18    275.0    1  30.200001  0.018618       NaN  
        2011-01-24    275.0    0  30.070000 -0.004305  0.018618  
        2011-01-31    275.0    0  29.836000 -0.007782 -0.004305  
        2011-02-07    275.0    0  30.398600  0.018856 -0.007782  
...                     ...  ...        ...       ...       ...  
93379.0 2022-05-31  11600.0    1  16.510000  0.013505  0.072416  
        2022-06-06  11600.0    0  16.350000 -0.009691  0.013505  
        2022-06-13  11600.0    0  14.410000 -0.118654 -0.009691  
        2022-06-21  11600.0    1  14.890000  0.033310 -0.118654  
        2022-06-27  11600.0    0  14.760000 -0.008731  0.033310  

[328252 rows x 10 columns]

In [122]:
dfw_etfs=dfw_etfs.reorder_levels(["DATE","PERMNO"]).sort_index().dropna()
dfw_etfs #weekly returns df

TICKER         PRC        VOL       ASKHI       BIDLO  \
DATE       PERMNO                                                            
2011-01-24 10113.0  b'AADR'  -30.070000        0.0   30.120001   30.020000   
           11264.0  b'RETL'   56.910000      400.0   56.910000   56.910000   
           11407.0   b'LIT'   21.903999   160000.0   21.969999   21.629999   
           11996.0  b'EMLC'   26.370001    73500.0   26.379999   26.230000   
           12035.0  b'AMLP'   16.160000   656800.0   16.180000   16.059999   
...                     ...         ...        ...         ...         ...   
2022-06-27 93366.0  b'PSCH'  141.589996    27573.0  142.253693  139.195007   
           93367.0  b'PSCD'   79.458702     2228.0   80.010002   79.070000   
           93376.0  b'EUSA'   72.937401    25431.0   73.559998   72.620003   
           93377.0  b'EIDO'   22.889999  1047301.0   22.990000   22.820000   
           93379.0  b'EPOL'   14.760000   140237.0   14.880000   14.690500   

                     SHROUT  DOW     ABS PRC       RET      LAGR  
DATE       PERMNO                                                 
2011-01-24 10113.0    275.0    0   30.070000 -0.004305  0.018618  
           11264.0    100.0    0   56.910000  0.004944  0.022941  
           11407.0   6200.0    0   21.903999 -0.048480  0.030900  
           11996.0    200.0    0   26.370001 -0.002553  0.008295  
           12035.0  35150.0    0   16.160000 -0.004313  0.007330  
...                     ...  ...         ...       ...       ...  
2022-06-27 93366.0   2420.0    0  141.589996  0.081418  0.018673  
           93367.0    340.0    0   79.458702  0.067563 -0.044667  
           93376.0   5550.0    0   72.937401  0.044799 -0.004989  
           93377.0  18850.0    0   22.889999 -0.007802  0.018094  
           93379.0  11600.0    0   14.760000 -0.008731  0.033310  

[327156 rows x 10 columns]

In [123]:
dfw_etfs["MKTCAP"] = abs(dfw_etfs["PRC"])*dfw_etfs["SHROUT"]
dfw_etfs["Quintile"] = dfw_etfs["MKTCAP"].groupby("DATE").apply(quintiles)

In [124]:
mktcap_params=dfw_etfs.groupby(["Quintile","DATE"]).apply(regfun)
mktcap_params

Intercept      LAGR
Quintile DATE                           
1        2011-01-24  -0.004559 -0.268235
         2011-01-31  -0.004667  0.005229
         2011-02-07   0.009114 -0.100125
         2011-02-14  -0.000592  0.294047
         2011-02-22  -0.005519 -0.484453
...                        ...       ...
4        2022-05-31   0.035167 -0.557892
         2022-06-06   0.001544 -0.007192
         2022-06-13  -0.080947  0.329930
         2022-06-21  -0.009795 -0.094061
         2022-06-27   0.028762  0.598936

[2388 rows x 2 columns]

<h3> Results </h3>

Again, there is no clean pattern between groups in effect of reversal. Smallest cap etfs seem to have the biggest reversal effect which is consistent with the result from daily data.

In [125]:
mktcap_stats=mktcap_params.loc[:,"LAGR"].groupby("Quintile").describe()
mktcap_stats

count      mean       std        min       25%       50%       75%  \
Quintile                                                                       
1         597.0 -0.048979  0.978163 -10.087305 -0.336504 -0.009944  0.297971   
2         597.0 -0.025268  1.351959 -15.826408 -0.285990 -0.002850  0.245306   
3         597.0 -0.039398  0.904125  -7.436026 -0.296415 -0.018522  0.239921   
4         597.0 -0.010498  0.604019  -4.229597 -0.252907 -0.007565  0.231249   

                max  
Quintile             
1         10.460993  
2         14.351101  
3          6.715168  
4          7.496752

When we only look at the largest market cap group, the average slope coefficient is -0.010498, meaning there is a reversal effect. However, the result is not statistically significant as the t-stats is -0.4246.

In [126]:
high_cap = mktcap_stats.loc[4,]
tstats = high_cap.loc["mean"]/(high_cap.loc["std"]/np.sqrt(high_cap.loc["count"]))
high_cap.loc["tstats"] = tstats
high_cap

count     597.000000
mean       -0.010498
std         0.604019
min        -4.229597
25%        -0.252907
50%        -0.007565
75%         0.231249
max         7.496752
tstats     -0.424669
Name: 4, dtype: float64

When we only look at the smallest market cap group, the average slope coefficient is -0.04898, meaning there is a reversal effect. However, the result is not statistically significant as the t-stats is -1.223.

In [127]:
low_cap = mktcap_stats.loc[1,]
tstats = low_cap.loc["mean"]/(low_cap.loc["std"]/np.sqrt(low_cap.loc["count"]))
low_cap.loc["tstats"] = tstats
low_cap

count     597.000000
mean       -0.048979
std         0.978163
min       -10.087305
25%        -0.336504
50%        -0.009944
75%         0.297971
max        10.460993
tstats     -1.223459
Name: 1, dtype: float64

The result for 3rd quartile group is not statistically significant as the t-stats is -1.065.

In [128]:
highmid_cap = mktcap_stats.loc[3,]
tstats = highmid_cap.loc["mean"]/(highmid_cap.loc["std"]/np.sqrt(highmid_cap.loc["count"]))
highmid_cap.loc["tstats"] = tstats
highmid_cap

count     597.000000
mean       -0.039398
std         0.904125
min        -7.436026
25%        -0.296415
50%        -0.018522
75%         0.239921
max         6.715168
tstats     -1.064717
Name: 3, dtype: float64

The result for 2nd quartile group is not statistically significant as the t-stats is -0.457.

In [129]:
lowmid_cap = mktcap_stats.loc[2,]
tstats = lowmid_cap.loc["mean"]/(lowmid_cap.loc["std"]/np.sqrt(lowmid_cap.loc["count"]))
lowmid_cap.loc["tstats"] = tstats
lowmid_cap

count     597.000000
mean       -0.025268
std         1.351959
min       -15.826408
25%        -0.285990
50%        -0.002850
75%         0.245306
max        14.351101
tstats     -0.456653
Name: 2, dtype: float64

<h3> The difference between group 1 and group 4 </h3>

The difference in reversal effect between highest and smallest group is not significant either as t stats = -1.186.

In [130]:
mktcap_diff = mktcap_params.loc[1,"LAGR"] - mktcap_params.loc[4,"LAGR"] 
smallminuslarge_stats=mktcap_diff.describe()
tstats_diff = smallminuslarge_stats.loc["mean"]/(smallminuslarge_stats.loc["std"]/np.sqrt(smallminuslarge_stats.loc["count"]))
smallminuslarge_stats.loc["tstats"]=tstats_diff
smallminuslarge_stats

count     597.000000
mean       -0.038481
std         0.793076
min        -8.901724
25%        -0.204793
50%        -0.004880
75%         0.174926
max         4.628138
tstats     -1.185554
Name: LAGR, dtype: float64

<h2> Conclusion </h2>

There is no clean pattern in reversal bewteen groups, i.e. a smaller cap etfs should have more reversal effect than a larger cap etf. However, when the daily returns are examined, the reversal effect is only significant in the smallest cap group (25%). When a longer time horizon is considered, the effect became insignificant, suggesting that the reversal effect in small cap maybe more prominent in shorter time horizon.

<h2> Portfolio Analysis </h2>

From the previous analysis, we know that only small cap ETF have the reversal effect. Thus, we are going to build a portfolio that only contains ETFs with a small cap. As usual, we will group the ETFs each day according to their last day's return, we are going to long the lowest return group and short the highest return group.

In [131]:
small_cap_etf = etf_clean.loc[etf_clean['Quintile'] == 1]
small_cap_etf

TICKER         PRC       VOL       ASKHI      BIDLO  \
DATE       PERMNO                                                          
2011-01-04 10113.0  b'AADR'   30.010000   22200.0   30.350000  29.910000   
           11264.0  b'RETL'  -57.290001       0.0   57.340000  57.240002   
           11996.0  b'EMLC'   26.650000  202500.0   26.770000  26.580000   
           12059.0  b'SCHR'   49.278999    4000.0   49.387001  49.277000   
           12109.0  b'EWZS'   30.309999   33400.0   30.400000  29.850100   
...                     ...         ...       ...         ...        ...   
2022-06-30 93359.0  b'PSCM'   58.410000     940.0   58.410000  57.340000   
           93362.0  b'PSCI'   81.503799    1298.0   81.755096  80.224998   
           93364.0  b'PSCC'  100.889999    2526.0  101.000000  99.339996   
           93365.0  b'PSCU'   57.470001     656.0   57.470001  56.630001   
           93367.0  b'PSCD'   74.748596    1299.0   75.150002  74.610001   

                         RET  SHROUT      LAGR        MKTCAP Quintile  
DATE       PERMNO                                                      
2011-01-04 10113.0 -0.001763   275.0  0.007473   8252.750063        1  
           11264.0 -0.021876   100.0  0.020051   5729.000092        1  
           11996.0  0.003011   200.0 -0.003301   5329.999924        1  
           12059.0 -0.000365   700.0  0.000264  34495.299530        1  
           12109.0 -0.000659  1250.0  0.014337  37887.499332        1  
...                      ...     ...       ...           ...      ...  
2022-06-30 93359.0 -0.000342   310.0 -0.012129  18107.099953        1  
           93362.0  0.011590   790.0 -0.010559  64388.001556        1  
           93364.0  0.001836   450.0  0.002839  45400.499725        1  
           93365.0  0.004248   400.0 -0.000578  22988.000488        1  
           93367.0 -0.016505   340.0 -0.017668  25414.522705        1  

[396204 rows x 10 columns]

In [132]:
small_cap_etf['Quintile'] = etf_clean["LAGR"].groupby("DATE").apply(quintiles)
small_cap_etf

<ipython-input-132-7a8378943b9d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_cap_etf['Quintile'] = etf_clean["LAGR"].groupby("DATE").apply(quintiles)


TICKER         PRC       VOL       ASKHI      BIDLO  \
DATE       PERMNO                                                          
2011-01-04 10113.0  b'AADR'   30.010000   22200.0   30.350000  29.910000   
           11264.0  b'RETL'  -57.290001       0.0   57.340000  57.240002   
           11996.0  b'EMLC'   26.650000  202500.0   26.770000  26.580000   
           12059.0  b'SCHR'   49.278999    4000.0   49.387001  49.277000   
           12109.0  b'EWZS'   30.309999   33400.0   30.400000  29.850100   
...                     ...         ...       ...         ...        ...   
2022-06-30 93359.0  b'PSCM'   58.410000     940.0   58.410000  57.340000   
           93362.0  b'PSCI'   81.503799    1298.0   81.755096  80.224998   
           93364.0  b'PSCC'  100.889999    2526.0  101.000000  99.339996   
           93365.0  b'PSCU'   57.470001     656.0   57.470001  56.630001   
           93367.0  b'PSCD'   74.748596    1299.0   75.150002  74.610001   

                         RET  SHROUT      LAGR        MKTCAP Quintile  
DATE       PERMNO                                                      
2011-01-04 10113.0 -0.001763   275.0  0.007473   8252.750063        2  
           11264.0 -0.021876   100.0  0.020051   5729.000092        4  
           11996.0  0.003011   200.0 -0.003301   5329.999924        1  
           12059.0 -0.000365   700.0  0.000264  34495.299530        1  
           12109.0 -0.000659  1250.0  0.014337  37887.499332        4  
...                      ...     ...       ...           ...      ...  
2022-06-30 93359.0 -0.000342   310.0 -0.012129  18107.099953        1  
           93362.0  0.011590   790.0 -0.010559  64388.001556        1  
           93364.0  0.001836   450.0  0.002839  45400.499725        4  
           93365.0  0.004248   400.0 -0.000578  22988.000488        3  
           93367.0 -0.016505   340.0 -0.017668  25414.522705        1  

[396204 rows x 10 columns]

In [133]:
small_cap_port = small_cap_etf.groupby(['Quintile','DATE'])['RET'].mean()
small_cap_port.dropna(inplace=True)
small_cap_port.head()

Quintile  DATE      
1         2011-01-04    0.001023
          2011-01-05    0.002059
          2011-01-06   -0.007537
          2011-01-07   -0.006650
          2011-01-10   -0.002198
Name: RET, dtype: float64

In [134]:
lowminushigh = small_cap_port.loc[1] - small_cap_port.loc[4]
port_describe = pd.DataFrame(lowminushigh.describe())

The result below describe that the average daily return is about 9 basis point, with a standard deviation of 2.4% and a sharpe ratio of 0.037

In [135]:
port_describe.loc['sharpe'] = port_describe.loc['mean'] / port_describe.loc['std']
port_describe

RET
count   2892.000000
mean       0.000925
std        0.024874
min       -0.268633
25%       -0.007887
50%        0.001040
75%        0.010249
max        0.312648
sharpe     0.037199

<h2> Summarize </h2>

| Test Method | b_1(form a group) | t_statistic(b_1) 
| :-: | :-: | :-: |
| daily_group1 | -0.021546 | -2.185840 |
| daily_group2 | -0.005475 | -0.559276 |
| daily_group3 | -0.013571 | -1.357350 | 
| daily_group4 | -0.005685 | -0.642602|
| daily_diff | -0.015861 | -2.467833 |
| weekly_group1 | -0.048979 | -1.223459 |
| weekly_group2 | -0.025268 | -0.456653 |
| weekly_group3 | -0.039398 | -1.064717 | 
| weekly_group4 | -0.010498 | -0.424669 |
| weekly_diff | -0.038481 | -1.185554 |

<h3> New portofolio:</h3>  

- Mean:0.000925    
- Std:0.024874     
- Sharpe ratio:0.037199 